---
- name: Configure systemd service for nginx
  hosts: ocean
  become: true
  gather_facts: true

  vars:
    image: nginx
    version: 1.27.3-alpine
    service: nginx
    path_data01: /data01/services
    path_home: "{{ path_data01 }}/{{ service }}"

  tasks:

    - name: Ensure basedir exists
      ansible.builtin.file:
        path: "{{ path_home }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure directory exists with correct ownership and permissions
      ansible.builtin.file:
        path: "{{ path_home }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
      - logs
      - conf
      - conf.d

    - name: Create config files
      ansible.builtin.template:
        src: "files/nginx/{{ item }}"
        dest: "{{ path_home }}/{{ item }}"
        mode: '0644'
      with_items:
      - nginx.conf
      - conf.d/proxy_hostname.conf
      notify:
        - Reload systemd daemon
        - Restart service

    - name: Create systemd service and timer
      ansible.builtin.template:
        src: "files/nginx/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - nginx.service
      notify:
        - Reload systemd daemon
        - Restart service

  handlers:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart service
      ansible.builtin.systemd:
        name: nginx.service
        state: restarted
