---
- name: Configure systemd service for tautulli
  hosts: ocean
  become: true
  vars:
    service: tautulli
    image: linuxserver/tautulli
    version: latest
    tautulli_port: 8905
    tautulli_api_key: 11c4a8c245984a6cb2b96414cac61923
    exporter_service: tautulli-exporter
    exporter_image: nwalke/tautulli_exporter
    exporter_version: latest
    exporter_port: 8913
    data: /data01
    files: files/ocean-tautulli
    incoming: "{{ data }}/incoming"
    complete: "{{ data }}/complete"
    home: "{{ data }}/services/{{ service }}"
    plex_logs: "{{ data }}/services/{{ service }}/config/Library/Application Support/Plex Media Server/Logs"
    user: media

  tasks:

    - name: Ensure basedir exists
      ansible.builtin.file:
        path: "{{ home }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Create config files
      ansible.builtin.template:
        src: "{{ files }}/config.ini.j2"
        dest: "{{ home }}/config.ini"
        mode: '0644'
      notify:
        - Reload tautulli systemd daemon
        - Restart tautulli service

    - name: Create tautulli systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - tautulli.service
      notify:
        - Reload tautulli systemd daemon
        - Restart tautulli service

    - name: Create exporter systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - tautulli-exporter.service
      notify:
        - Reload exporter systemd daemon
        - Restart exporter service

  handlers:
    - name: Reload tautulli systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart tautulli service
      ansible.builtin.systemd:
        name: tautulli.service
        state: restarted

    - name: Reload exporter systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart exporter service
      ansible.builtin.systemd:
        name: tautulli-exporter.service
        state: restarted
