---
- name: Gitlab Installation
  hosts: gitlab
  become: true
  gather_facts: true
  vars:
    service: gitlab
    services:
    - "{{ service }}.service"
    hostname: "{{ service }}.home"
    gitlab_external_url: "https://{{ hostname }}"
    gitlab_version: "17.7.2-ce.0"
    path_home: "/data01/services/{{ service }}"
    path_config: "{{ path_home }}/config"
    path_logs: "{{ path_home }}/logs"
    path_data: "{{ path_home }}/data"

  tasks:
    - name: Required packages pre-installation
      block:
      - name: Update apt cache
        apt:
          update_cache: yes
          cache_valid_time: 3600

      - name: Install required packages
        apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - openssh-server
            - perl
            - wget
          state: present

    - name: gitlab dirs and config
      block:
      - name: Ensure gitlab_home exists
        ansible.builtin.file:
          path: "{{ path_home }}"
          state: directory
          mode: '0755'

      - name: Ensure subdirectories exist
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
        - "{{ path_config }}"
        - "{{ path_logs }}"
        - "{{ path_data }}"

      - name: Create config files
        ansible.builtin.template:
          src: "files/gitlab-docker/{{ item }}"
          dest: "{{ path_home }}/{{ item }}"
          mode: '0644'
        with_items:
          - root_password.txt
          - gitlab.rb
        notify:
          - Restart gitlab service


    - name: GitLab installation block
      block:

        - name: Add GitLab CE repository
          become: yes
          shell: |
            curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

        - name: Install GitLab CE
          apt:
            name: "gitlab-ce={{ gitlab_version }}"
            state: present
            update_cache: yes
          environment:
            EXTERNAL_URL: "{{ gitlab_external_url }}"










    - name: Create systemd service
      ansible.builtin.template:
        src: "files/gitlab-docker/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      loop: "{{ services }}"
      notify:
        - Reload systemd daemon
        - Restart gitlab service

  handlers:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart gitlab service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services }}"
