---
- name: Configure systemd service for ethtool settings
  hosts: ocean
  become: true
  gather_facts: true
  tasks:
    - name: Ensure required packages are installed (Debian/Ubuntu)
      apt:
        name:
          - zfsutils-linux
          - zfs-zed
          - zfs-initramfs
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Load ZFS kernel module if not already loaded
      ansible.builtin.shell: "lsmod | grep -q '^zfs' || modprobe zfs"
      changed_when: false

    - name: Check if ZFS tools are available
      command: zpool --version
      register: zfs_check
      failed_when: zfs_check.rc != 0

    - name: Report ZFS installation status
      debug:
        msg: "ZFS tools are successfully installed and available."

    - name: Create systemd mount for data01
      ansible.builtin.template:
        src: "files/ocean-data01/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - data01.mount

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start ZFS-related services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - zfs-import-cache.service
        - zfs-import-scan.service
        - zfs-mount.service
        - zfs.target
        - data01.mount