---
- name: Create Ramdisk
  hosts: ocean
  become: true

  tasks:
  - name: Ensure /mnt/ramdisk directory exists
    ansible.builtin.file:
      path: /mnt/ramdisk
      state: directory
      owner: root
      group: root
      mode: '1777'

  - name: Add /mnt/ramdisk to /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "tmpfs /mnt/ramdisk tmpfs defaults,size=32G,noatime,nodev,nosuid 0 0"
      regexp: "^tmpfs\\s+/mnt/ramdisk\\s+tmpfs\\s+"
      state: present

  - name: Mount /mnt/ramdisk
    ansible.builtin.mount:
      path: /mnt/ramdisk
      src: tmpfs
      fstype: tmpfs
      opts: "defaults,size=32G,noatime,nodev,nosuid"
      state: mounted
