- name: Proxmox VM Setup
  become: yes
  hosts: all

  tasks:
  - name: Install QEMU Guest Agent
    apt:
      name: qemu-guest-agent
      state: latest
      force: yes
    register: apt_status
    until: apt_status is succeeded
    delay: 6
    retries: 30
    ignore_errors: yes
