---
- name: docker
  hosts: docker

  tasks:
  - name: install or update docker
    become: yes
    block:

    - name: apt-get update
      apt: update_cache=yes

    - name: package install
      apt:
        pkg:
          [ docker ]

    - name: docker configs
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "journald"
          }


    - name: Enable and Start service
      systemd:
        enabled: yes
        state: restarted
        name: docker
        daemon_reload: true
