- name: Cilium
  hosts: k8s
  strategy: free
  become: true

  vars_files:
    - vars_kube.yaml

# cilium specific vars
  vars:
    cilium_binpath: "/usr/local/bin"
    cilium_org: cilium
    cilium_repo: cilium-cli
    cilium_version: "v0.16.4"
    cilium_filename: "{{ cilium_org }}-linux-amd64.tar.gz"
    cilium_project_url: https://github.com/{{ cilium_org }}/{{ cilium_repo }}/releases/download/{{ cilium_version }}/{{ cilium_filename }}

  tasks:
  - name: Create tempdir
    ansible.builtin.tempfile:
      state: directory
      suffix: _dwnld
    register: tempfolder_1

  - name: Installing {{ cilium_repo }} {{ cilium_version }}
    ansible.builtin.unarchive:
      remote_src: true
      src: "{{ cilium_project_url }}"
      dest: "{{ tempfolder_1.path }}"
      keep_newer: true

  - name: Mv files to bindir
    ansible.builtin.find:
      paths: "{{ tempfolder_1.path }}"
      patterns: "cilium*"
    register: cilium_files

  - name: Mv files to bindir
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item.path }}"
      dest: "{{ cilium_binpath }}/{{ item.path | basename }}-{{ cilium_version }}"
      mode: "0755"
    with_items: "{{ cilium_files.files }}"

  - name: Ln files to bindir
    ansible.builtin.file:
      state: link
      force: true
      src: "{{ cilium_binpath }}/{{ item.path | basename }}-{{ cilium_version }}"
      dest: "{{ cilium_binpath }}/{{ item.path | basename }}"
    with_items: "{{ cilium_files.files }}"

  - name: Rm tempdir
    ansible.builtin.file:
      state: absent
      path: "{{ tempfolder_1.path }}"
