---
- name: Configure systemd service for ethtool settings
  hosts: ocean
  become: true
  gather_facts: true
  tasks:

  - name: Ensure group 'media' with GID 1001 exists
    group:
      name: media
      gid: 1001
      state: present

  - name: Ensure user 'media' with UID 1001 exists and is part of group 'media'
    user:
      name: media
      uid: 1001
      group: media
      state: present

  - name: Ensure /data01 directory exists
    file:
      path: /data01
      state: directory
      owner: media
      group: media
      mode: '0755'

  - name: Create systemd mount for data01
    ansible.builtin.template:
      src: "files/ocean-data01/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - data01.mount

  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable and start service
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
    - data01.mount
