---
- name: Configure systemd service for overseerr
  hosts: ocean
  become: true
  gather_facts: true

  vars:
    image: sctx/overseerr
    version: latest
    service: overseerr
    files: files/ocean-overseerr
    data: /data01
    home: "{{ data }}/services/{{ service }}"
    port: 5055
    user: media

  tasks:

  - name: Ensure basedir exists
    ansible.builtin.file:
      path: "{{ home }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Ensure directory exists with correct ownership and permissions
    ansible.builtin.file:
      path: "{{ home }}/{{ item }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    with_items:
    - config

  - name: Create systemd service
    ansible.builtin.template:
      src: "{{ files }}/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - overseerr.service
    notify:
    - Reload systemd daemon
    - Restart service

  handlers:
  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart service
    ansible.builtin.systemd:
      name: overseerr.service
      state: restarted
