---
- name: Configure Grafana Monitoring Dashboard using Docker Compose
  hosts: ocean
  become: true
  gather_facts: true

  vars_files:
    - vault_secrets.yaml

  vars:
    service: grafana
    image: grafana/grafana
    version: 11.5.4
    port_int: 3000
    port_ext: 8910
    plugins: "marcusolsson-treemap-panel 2.0.0"
    data: /data01
    files: files/grafana-compose
    home: "{{ data }}/services/{{ service }}"
    user: grafana
    uid: 1001
    gid: 1001

  tasks:

  - name: Ensure base directory exists
    ansible.builtin.file:
      path: "{{ home }}"
      state: directory
      owner: "{{ uid }}"
      group: "{{ gid }}"
      mode: '0755'

  - name: Ensure grafana and mysql subdirectories exist
    ansible.builtin.file:
      path: "{{ home }}/{{ item }}"
      state: directory
      owner: "{{ uid }}"
      group: "{{ gid }}"
      mode: '0755'
    with_items:
    - logs
    - plugins
    - data
    - mysql-data
    - mysql-logs
    - mysql-conf
    - provisioning
    - provisioning/users
