- name: Generate kubeconfig for kube-scheduler
  delegate_to: localhost
  command: >
    kubectl config set-cluster kubernetes
    --certificate-authority={{ cfssl }}/ca.pem
    --embed-certs=true
    --server=https://{{ APISERVER }}:6443
    --kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig

- name: Set credentials for kube-scheduler
  delegate_to: localhost
  command: >
    kubectl config set-credentials system:kube-scheduler
    --client-certificate={{ cfssl }}/kube-scheduler.pem
    --client-key={{ cfssl }}/kube-scheduler-key.pem
    --embed-certs=true
    --kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig

- name: Set context for kube-scheduler
  delegate_to: localhost
  command: >
    kubectl config set-context system:kube-scheduler@kubernetes
    --cluster=kubernetes
    --user=system:kube-scheduler
    --kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig

- name: Use the kube-scheduler context
  delegate_to: localhost
  command: >
    kubectl config use-context system:kube-scheduler@kubernetes
    --kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig
