- name: Experimental x-12
  hosts: all
  vars:
    iface_names: []
  #     cni:
  #       conf: /etc/cni/net.d
  #       bin: /opt/cni/bin
  #     kubernetes:
  #       conf: /etc/kubernetes/config
  #       static: /etc/kubernetes/manifests
  #       data: /var/lib/kubernetes
  #       lock: /var/run/kubernetes
  #     system:
  #       bin: /usr/local/bin
  #     kube-proxy:
  #       data: /var/lib/kube-proxy

  tasks:
    # - name: print debug
    #   debug:
    #     msg: "{{ ansible_facts['eno1']['module'] }}"
    - name: print debug
      set_fact:
        iface_names: "{{ iface_names + [item] }}"
      when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
      with_items:
        - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

    # - name: print debug
    #   debug:
    #     msg: "{{ hostvars[inventory_hostname]['ansible_' + item]['module'] }}"
    #   when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
    #   with_items:
    #     - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

    - name: print debug
      debug:
        msg: "{{ sorted_ifaces[-2:] }}"
      vars:
        sorted_ifaces: "{{ iface_names | sort }}"
