# tasks file for common
---
- name: Etcd
  become: true
  block:

    - name: Tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ query('fileglob', {{ playbook_dir }}/roles/etcd/tasks/*.yaml) | reject('main') }}"