# handlers file for dns
---
- name: config_check
  become: true
  block:

    - name: Config Check
      ansible.builtin.shell: /usr/sbin/named-checkconf

    - name: Check forwards
      ansible.builtin.shell: /usr/sbin/named-checkzone  "{{ item.forward }}" "{{ item.forward_file }}"
      # ansible.builtin.shell: /usr/sbin/named-checkzone  home /var/lib/bind/home.zone
      with_items: "{{ zones_files }}"

    - name: Check reverses
      ansible.builtin.shell: /usr/sbin/named-checkzone "{{ item.reverse }}"   "{{ item.reverse_file }}"
      # ansible.builtin.shell: /usr/sbin/named-checkzone 1.168.192.in-addr.arpa /var/lib/bind/db.rev.1.168.192.in-addr.arpa
      with_items: "{{ zones_files }}"
