- name: Configure HAProxy and keepalived for HA setup
  hosts: k8s_controller
  become: yes
  any_errors_fatal: true
  tasks:
  - name: Install keepalived and haproxy
    apt:
      name:
      - keepalived
      - haproxy
      state: present
      update_cache: yes

  - name: Create directories
    file:
      state: directory
      path: "{{ item }}"
      owner: haproxy
      group: haproxy
      mode: '0700'
    with_items:
    - /etc/keepalived
    - /etc/haproxy
    - /etc/ssl/haproxy

  - name: Configure keepalived
    template:
      src: files/keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
    notify:
    - Reload systemd daemon
    - Restart keepalived

  - name: Check for VIP on the interface
    shell: "ip addr show | grep {{ vip }}"
    register: vip_check
    failed_when: vip_check.rc != 0 and vip_check.rc != 1 # Allow both success and 'not found' status codes
    ignore_errors: yes

  - name: Print which host holds the VIP
    debug:
      msg: "The host {{ inventory_hostname }} holds the VIP {{ vip }}"
    when: vip_check.rc == 0

  - name: Configure HAProxy
    template:
      src: files/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    vars:
      pem_exists: "{{ pem_file_stat.stat.exists }}"
    notify:
    - Restart haproxy

  handlers:
  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart haproxy
    ansible.builtin.systemd:
      name: haproxy
      state: restarted
      enabled: yes

  - name: Restart keepalived
    ansible.builtin.systemd:
      name: keepalived
      state: restarted
      enabled: yes
