- name: NFS server install and configure mounts
  hosts: all
  become: yes
  tasks:
    - name: install nfs server
      apt:
        name: [ nfs-kernel-server ]
        state: present
        update_cache: yes

    - name: mkdir the nfsv4 share root
      file:
        dest: "/srv/nfs4/root"
        state: directory
        mode: 0777
        owner: nobody
        group: nogroup

    - name: Ensure required entries are made to hosts file
      lineinfile:
        path: /etc/exports
        state: present
        line: "{{ item }}"
      with_items:
        - '/srv/nfs4  *(rw,sync,no_subtree_check,crossmnt,fsid=0)'
        - '/srv/nfs4/root *(rw,sync,no_subtree_check)'

    - name: systemd enable and restart nfs-server
      systemd:
        name: nfs-server
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Re-export the share
      command: exportfs -rav
