## This file is a template remove the .template to use the file
libraries:                                      # This is called out once within the config.yml file                                       
  Movies:                                       # Each library must match the Plex library name
    metadata_path:
    - file: config/Movies.yml                   # This is a local file on the system
    - folder: config/movies/                    # This is a local directory on the system
    - pmm: seasonal
    - pmm: basic                                # This is a file within the defaults folder in the Repository
    - pmm: imdb                                 # This is a file within the defaults folder in the Repository
    - pmm: franchise
      template_variables:
        collection_order: release
        build_collection: true
        radarr_add_missing: true
    - pmm: studio
    - pmm: tautulli
    - pmm: content_rating_us
    - pmm: oscars
    - pmm: cannes
    - pmm: sundance
    - pmm: director
    operations:
      delete_unmanaged_collections: true
    overlay_path:
    - remove_overlays: false                    # Set this to true to remove all overlays
    - file: config/Overlays.yml                 # This is a local file on the system
    - pmm: ribbon                               # This is a file within the defaults folder in the Repository
playlist_files:
- file: config/playlists.yml
- pmm: playlist                                 # This is a file within the defaults folder in the Repository
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 2
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
webhooks:                                       # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.1.143:32400
  token: Bgwuadg8qBRS1EVYSyws
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
  db_cache:
  verify_ssl:
tmdb:                                           # REQUIRED for the script to run
  apikey: 9d6b8a6a0342e58c7eb6f8e8d9e5f7c9
  language: en
  cache_expiration: 60
  region:
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.1.143:8905
  apikey: 11c4a8c245984a6cb2b96414cac61923
radarr:                                         # Can be individually specified per library as well
  url: http://192.168.1.143:8903
  token: ################################
  add_missing: false
  add_existing: true
  root_folder_path: /movies
  monitor: true
  availability: announced
  quality_profile: HD  REMUX + WEB
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
  monitor_existing: false
sonarr:                                         # Can be individually specified per library as well
  url: http://192.168.1.143:8904
  token: f04a996effa8494aa68712bdb0b33a6f
  add_missing: false
  add_existing: true
  root_folder_path: S:/TV Shows
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
  monitor_existing: false
