- name: List handlers
  hosts: localhost

  vars:

    pb_file: "{{ query('fileglob', '{{playbook_dir}}/roles/dns/tasks/*.yaml') }}"
    pb_dict: "{{ lookup('file', pb_file)|from_yaml }}"
    pb_handlers: "{{ dict(pb_dict|json_query('[].[name,handlers[].name]')) }}"

  tasks:

    - ansible.builtin.debug:
        msg: |

          playbook: {{ pb_file }}

          {% for play,handlers in pb_handlers.items() %}
          play {{ '#' }}{{ loop.index }} {{ play }}
              HANDLERS: {{ handlers|d([], true)|join(', ') }}

          {% endfor %}
      when: pb_file is exists
