- hosts: all
  roles:
    - {role: handlers}
    - {role: common}

- hosts: dns
  roles:
    - {role: dns}
    - {role: dhcp-server}

- hosts: dns
  roles:
    - {role: dns}
    - {role: dhcp-server}
