- hosts: all
  roles:
    - {role: common, tags: common}

- hosts: dns
  roles:
    - {role: common, tags: common}
    - {role: dns , tags: dns}
    - {role: dhcp-server, tags: dhcp}
    - {role: dnsmasq, tags: dnsmasq}
