- hosts: all
  roles:
    - {role: common, tags: common}

- hosts: dns
  roles:
    - {role: common, tags: common}
    - {role: dns, tags: dns}
    - {role: dhcp-server, tags: dhcp}
    - {role: dnsmasq, tags: dnsmasq}

- hosts: etcd
  roles:
    - {role: common, tags: common}
    - {role: k8s_certs, tags: k8s_certs}
    - {role: etcd, tags: etcd}

- hosts: local, k8s
  roles:
    - {role: k8s_certs, tags: k8s_certs}

- hosts: k8s_controller
  roles:
    - {role: common, tags: common}
    - {role: k8s_certs, tags: k8s_certs}
    - {role: k8s_controller, tags: k8s_controller}

- hosts: k8s_worker
  roles:
    - {role: common, tags: common}
    - {role: k8s_worker, tags: k8s_worker}
