---
- hosts: all
  # gather_facts: no
  vars:
    iface:
      stdout: eth0
    auth_zone: home

  tasks:

  # - name: hostvars print
  #   debug:
  #     var: "{{item}}"
  #   with_items:
  #   - hostvars[inventory_hostname]
  #   - hostvars[inventory_hostname]["ansible_default_ipv4"]["address"]

  - name: render
    template:
      src: roles/dnsmasq/files/etc/dnsmasq.conf
      dest: /dev/null
    register: rendered_template

  - debug:
      var: rendered_template
