---
apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
    name: ambassador
    namespace: ambassador
spec:
  version: "*"
  installOSS: true
  helmValues:
    replicaCount: 1
    deploymentStrategy:
        type: Recreate
    service:
        type: NodePort
        ports:
            - name: http
              port: 80
              hostPort: 80
              targetPort: 8080
            - name: https
              port: 443
              hostPort: 443
              targetPort: 8443