  - name: Config
    block:

      - name: set dict for zones
        ansible.builtin.set_fact:
          zone_dir: "/var/lib/bind/"

      - name: rndc-key-write
        shell:
          creates: /etc/bind/rndc.key
          cmd: rndc-confgen -a -b 512

      - name: configs
        ansible.builtin.copy:
          force: yes
          src: bind9/{{ item  }}
          dest: /etc/bind/{{ item  }}
          owner: bind
          group: bind
          mode: 0644
        with_items:
          - named.conf.local
          - named.conf.options

      - name: make conf dirs
        ansible.builtin.file:
          path: "{{ zone_dir }}"
          state: directory
          owner: bind
          group: bind
          mode: 0755

      - name: write zone templates
        ansible.builtin.copy:
          force: yes
          dest: "{{ zone_dir }}/{{item}}"
          content: '{{ lookup("template", "{{ role_path }}/files/bind9/{{item}}.j2") }}'
          mode: 0644
          owner: bind
          group: bind
        with_items:
          - home.zone
          - cluster.local.zone
          - db.rev.1.168.192.in-addr.arpa

      - name: set dict for zones
        ansible.builtin.set_fact:
          zones_files:
            - { forward: 'home', forward_file: "{{ zone_dir }}/home.zone", reverse: "1.168.192.in-addr.arpa", reverse_file: "{{ zone_dir }}/db.rev.1.168.192.in-addr.arpa" }

      - name: set services dict for handler
        ansible.builtin.set_fact:
          local_services:
            - { name: 'named', enabled: true, state: 'restarted' }

      - name: set services dict for handler
        ansible.builtin.set_fact:
          services: "{{ services + local_services }}"

    notify:
      - dns_config_check
      - enable_and_restart
