# tasks file for bind9
---
- name: DNS server setup
  become: true
  block:

    - name: Tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ query('fileglob', {{ playbook_dir }}/roles/dns/tasks/*.yaml) | reject('main') }}"
      apply:
        notify:
          - Config Check
          - Restart bind9