# tasks file for bind9
---
- name: bind9 server setup
  become: true
  block:

    - name: Tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ query('fileglob', '{{playbook_dir}}/roles/dns/tasks/*.yaml') | reject('search', 'main') | list }}"
