  - name: Config
    block:

      # Make variables for the Kubernetes configfile
      - name: Get IP for a subset of hosts, store in PEERS_IP
        ansible.builtin.shell:
          cmd: ip route | awk '(/default/){print $5}'
        register: iface

      - name: set vars
        ansible.builtin.set_fact:
          auth_zone : 'home'

      - name: make conf dirs
        ansible.builtin.file:
          path: "{{ item }}"
          state: "{{ state | default('directory') }}"
          mode: 0755
        with_items:
        - /etc/dnsmasq

      - name: hostvars print
        debug:
          var: "{{item}}"
        with_items:
        - hostvars[inventory_hostname]


      - name: write out template files
        ansible.builtin.copy:
          force: yes
          dest: "{{ item }}"
          content: '{{ lookup("template", "{{ role_path }}/files{{ item }}") }}'
          mode: 0644
        with_items:
          - /etc/dnsmasq.conf
          - /etc/dnsmasq/dns_records.conf
          - /etc/systemd/system/dnsmasq.service

      - name: set services dict for handler
        ansible.builtin.set_fact:
          local_services:
            - { name: 'dnsmasq', enabled: True, state: 'restarted' }

      - name: set services dict for handler
        ansible.builtin.set_fact:
          services: "{{ services + local_services }}"

    notify:
      - enable_and_restart
