{
 "title": "Fail2ban",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(f2b_up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Currently Failed",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "f2b_jail_failed_current{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Currently Banned",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "f2b_jail_banned_current{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Banned Total Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_jail_banned_total{instance=~\"$host\"}",
     "legendFormat": "{{instance}} - {{jail}}"
    }
   ]
  },
  {
   "title": "Failed Currently",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "f2b_jail_failed_current{instance=~\"$host\"}",
     "legendFormat": "{{instance}} - {{jail}}"
    }
   ]
  },
  {
   "title": "Banned Currently",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "f2b_jail_banned_current{instance=~\"$host\"}",
     "legendFormat": "{{instance}} - {{jail}}"
    }
   ]
  },
  {
   "title": "Failed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "f2b_jail_failed_total{instance=~\"$host\"}",
     "legendFormat": "{{instance}} - {{jail}}"
    }
   ]
  },
  {
   "title": "Banned Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "f2b_jail_banned_total{instance=~\"$host\"}",
     "legendFormat": "{{instance}} - {{jail}}"
    }
   ]
  }
 ]
}