{
 "title": "Prowlarr",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_system_status{}" }
   ]
  },
  {
   "title": "Total Items",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_history_total{}" }
   ]
  },
  {
   "title": "Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Queries by App",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_user_agent_queries_total{}",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Grabs by App",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_user_agent_grabs_total",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  { "title": "Indexers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Grabs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_indexer_grabs_total", "legendFormat": "{{indexer}}" }
   ]
  },
  {
   "title": "Grabs Failed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_failed_grabs_total",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_queries_total{}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Queries Failed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_failed_queries_total",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  { "title": "Indexers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Indexers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_indexer_total{}" }
   ]
  },
  {
   "title": "Indexers Enabled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_enabled_total{}"
    }
   ]
  }
 ]
}