{
 "title": "ZFS",
 "description": "zfs arc zpool access time iops with multi node comparison",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ARC - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_data_misses{job=\"node_exporter\",instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{job=\"node_exporter\",instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "node",
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"node_exporter\",instance=~\"$node\"}",
     "legendFormat": "data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"node_exporter\",instance=~\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{job=\"node_exporter\",instance=~\"$node\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{job=\"node_exporter\",instance=~\"$node\"}",
     "legendFormat": "hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{job=\"node_exporter\",instance=~\"$node\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "ZPOOL - Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "node",
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_rtime{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - read"
    },
    {
     "expr": "irate(node_zfs_zpool_wtime{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - write"
    }
   ]
  },
  {
   "title": "ZPOOL - Ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "repeat": "node",
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_reads{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "irate(node_zfs_zpool_writes{job=\"node_exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  }
 ]
}