{
 "title": "ZFS Details",
 "description": "ZFS monitoring dashboard for Unraid",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "30s" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(zpool_stats_alloc{job='$job'}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZFS Pool Detail",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "zpool_stats_alloc{job='$job'}", "legendFormat": "__auto" },
    {
     "expr": "zpool_stats_checksum_errors{job='$job'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_stats_fragmentation{job='$job'}",
     "legendFormat": "__auto"
    },
    { "expr": "zpool_stats_free{job='$job'}", "legendFormat": "__auto" },
    {
     "expr": "zpool_stats_read_bytes{job='$job'}",
     "legendFormat": "__auto"
    },
    { "expr": "zpool_stats_size{job='$job'}", "legendFormat": "__auto" },
    {
     "expr": "zpool_stats_write_bytes{job='$job'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Growth by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zpool_stats_alloc{job='$job', vdev=\"root\"}[1d])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_alloc{job='$job', vdev=\"root\"}",
     "legendFormat": "{{name}} - Used"
    },
    {
     "expr": "zpool_stats_size{job='$job', vdev=\"root\"}",
     "legendFormat": "{{name}} - Size"
    },
    {
     "expr": "zpool_stats_free{job='$job', vdev=\"root\"}",
     "legendFormat": "{{name}} - Free"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"$job\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"$job\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "node_zfs_arc_mfu_size{job=\"$job\"}",
     "legendFormat": "Most Frequently Used"
    },
    {
     "expr": "node_zfs_arc_dnode_size{job=\"$job\"}",
     "legendFormat": "Dnode Size"
    },
    {
     "expr": "node_zfs_arc_mru_size{job=\"$job\"}",
     "legendFormat": "Most Recently Used"
    },
    {
     "expr": "node_zfs_arc_size{job=\"$job\"}",
     "legendFormat": "ARC Size"
    }
   ]
  },
  {
   "title": "ARC Demand - Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[$__rate_interval])/(rate(node_zfs_arc_demand_data_misses{job=\"$job\"}[$__rate_interval])+rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "ARC Demand - Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[$__rate_interval])/(rate(node_zfs_arc_demand_metadata_misses{job=\"$job\"}[$__rate_interval])+rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  { "title": "Scans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Pools Scans Finished",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "zpool_scan_stats_end_ts{state=~\"finished|canceled\", job=\"$job\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_start_ts{state=~\"finished|canceled\", job=\"$job\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_examined{state=~\"finished|canceled\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_errors{state=~\"finished|canceled\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_processed{state=~\"finished|canceled\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools Scans In Progress",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_start_ts{job=~'$job', state!~\"finished|canceled\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_remaining_t{state!~\"finished|canceled\", job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_errors{job=~'$job', state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_issued{job=~'$job', state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_pass_issued{job=~'$job', state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_processed{job=~'$job',state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_to_process{job=~'$job',state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_scan_stats_rate{job=~'$job',state!~\"finished|canceled\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool Stats - $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }, "repeat": "pool" },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_alloc{job='$job', vdev=\"root\", name=\"$pool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "zpool_stats_size{job='$job', vdev=\"root\", name=\"$pool\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "zpool_stats_free{job='$job', vdev=\"root\", name=\"$pool\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Pool Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(zpool_stats_read_bytes{job='$job', name=\"$pool\",vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(zpool_stats_read_ops{job='$job', name=\"$pool\", vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}} IOPS"
    },
    {
     "expr": "irate(zpool_stats_read_errors{job='$job', name=\"$pool\", vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}} Errors"
    }
   ]
  },
  {
   "title": "Total Reads Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_total_read{name=\"$pool\", job=\"$job\"}[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pool Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(zpool_stats_write_bytes{job='$job', name=\"$pool\",vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(zpool_stats_write_ops{job='$job', name=\"$pool\", vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}} IOPS"
    },
    {
     "expr": "irate(zpool_stats_write_errors{job='$job', name=\"$pool\", vdev=\"root\"}[$__rate_interval])",
     "legendFormat": "{{name}} Errors"
    }
   ]
  },
  {
   "title": "Total Writes Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 83 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zpool_latency_total_write{name=\"$pool\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "IO Stats - $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 }, "repeat": "pool" },
  {
   "title": "Sync Reads Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "sum  (increase(zpool_latency_sync_read{job=\"$job\", name=\"$pool\"}[$__rate_interval])) by(le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sync Writes Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 146 },
   "targets": [
    {
     "expr": "sum (increase(zpool_latency_sync_write{job='$job', name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Async Reads Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_async_read{job='$job', name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Async Writes Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_async_write{job='$job',name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Disk Reads Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_disk_read{job='$job', name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Disk Writes Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 166 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_disk_write{job='$job',name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Scrub Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_scrub{job='$job', name=\"$pool\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Trim Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 176 },
   "targets": [
    {
     "expr": "sum(increase(zpool_latency_trim{job='$job', name=\"$pool\"}[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}