- name: local cfssl cert generation
  hosts: local
  tasks:

  - name: Generate Kubernetes Control Plane CA TLS Certs
    block:

    - name: install cfssl
      community.general.homebrew:
        name: cfssl
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: install cfssl
      delegate_to: localhost
      become: true
      apt:
        name: golang-cfssl
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Certificate Authority
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/ca.pem"


    - name: The Admin Client Certificate
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | cfssljson -bare admin
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/admin.pem"

    - name: Controller Manager Client Certificate
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/kube-controller-manager.pem"

    - name: Kube Proxy Client Certificate
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/kube-proxy.pem"

    - name: Kube Aggregation Layer Certificate
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-aggregator-csr.json | cfssljson -bare kube-aggregator
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/kube-aggregator.pem"

    - name: Scheduler Client Certificate
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-scheduler-csr.json | cfssljson -bare kube-scheduler
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/kube-scheduler.pem"

    #### Bulding variables k8s_controller
    - name: Hostname expansion into dict of name:ip
      set_fact:
        HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
      loop: "{{ groups['k8s_controller'] + [APISERVER] }}"

    - name: debug
      debug:
        msg: "{{HOST_IP}}"

    - name: Flatten dict to formatted string, store PEERS_MAP
      set_fact:
        PEERS_MAP: "{{ PEERS_MAP }}{{ (index > 0)|ternary(',','') }}{{ item.key }},{{ item.value }}"
      loop: "{{  HOST_IP | dict2items }}"
      loop_control:
        index_var: index

    # kube apiserver has many names, some services will also be listed in the SAN
    - name: API Server Certificate
      delegate_to: localhost
      shell:
        cmd: >-
          cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json
          -hostname=apiserver,{{HOST_IP['apiserver']}},127.0.0.1,{{ '.'.join(SERVICE_CLUSTER_IP_RANGE.split('.')[:3]) }}.1,{{KUBERNETES_HOSTNAMES}},{{PEERS_MAP}},"metrics-server.kube-system.svc"
          -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/kubernetes.pem"

    - name: Service Account Key Pair
      delegate_to: localhost
      shell:
        cmd: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes service-account-csr.json | cfssljson -bare service-account
        chdir: "{{ cfssl }}"
      args:
        creates: "{{ cfssl }}/service-account.pem"

    #### Bulding variables k8s
    - name: Hostname expansion into dict of name:ip
      set_fact:
        HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
      loop: "{{ groups['k8s'] }}"

    - name: debug
      debug:
        msg: "{{HOST_IP}}"

    # Node Client Certs
    - name: Client Certs
      delegate_to: localhost
      include: subtask_kube_node_certs.yaml file={{item}}
      with_inventory_hostnames:
      - k8s

    #### Bulding variables k8s
    - name: Hostname expansion into dict of name:ip
      set_fact:
        HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
      loop: "{{ groups['k8s'] }}"

    - name: debug
      debug:
        msg: "{{HOST_IP}}"

    # Node Client Certs
    - name: Client Certs
      delegate_to: localhost
      include: subtask_kube_node_certs.yaml file={{item}}
      with_inventory_hostnames:
      - k8s