  - name: UPS battery backups
    when: apcupsd is defined
    block:

    - name: print debug
      debug:
        msg: "APC UPSd software and config"

    - name: Install a suite of common tools
      apt:
        pkg: [apcupsd]

    - name: APCUPSd config
      copy:
        force: yes
        dest: "/etc/apcupsd/apcupsd.conf"
        content: |
          UPSNAME smartups1500
          UPSCABLE usb
          UPSTYPE usb
          MINUTES 7
          DEVICE
          POLLTIME 60

    - name: UPSd /etc/default
      copy:
        force: yes
        dest: "/etc/default/apcupsd"
        content: |
          ISCONFIGURED=yes

    - name: min time left script
      copy:
        force: yes
        mode: 0755
        dest: "/etc/apcupsd/runlimit"
        content: |
          #!/bin/bash
          # http://www.apcupsd.org/manual/manual.html#configure-options
          for host in ocean.home $(printf "node%03d " $(seq 1 6) | xargs -n1 | grep -vi $(hostname)) ; do ssh -l ubuntu ${host} 'sudo hostname' & done
          wait
          shutdown -h now

    - name: enable and restart services
      systemd:
        name: apcupsd
        state: restarted
        enabled: true
        daemon_reload: true