- name: IO-scheduler
  ignore_errors: true
  when: ansible_os_family == 'Linux'
  block:



  - name: Write io-scheduler script
    ansible.builtin.copy:
      force: yes
      dest: "/etc/systemd/system/io-scheduler.sh"
      mode: 0755
      content: |
        for SCH in /sys/block/*/queue/scheduler ; do
            echo "deadline" > "${SCH}" 2>/dev/null
        done
        for DEPTH in /sys/block/*/queue/nr_requests ; do
            echo "1024" > "${DEPTH}" 2>/dev/null
        done
        for RAHEAD in /sys/block/*/queue/read_ahead_kb ; do
            echo "4096" > "${RAHEAD}" 2>/dev/null
        done

  - name: Write io-scheduler service
    ansible.builtin.copy:
      force: yes
      dest: "/etc/systemd/system/io-scheduler.service"
      content: |
        [Unit]
        Description=Setup foo
        #After=network.target

        [Service]
        Type=oneshot
        ExecStart=sh -c /etc/systemd/system/io-scheduler.sh
        RemainAfterExit=true
        StandardOutput=journal

        [Install]
        WantedBy=multi-user.target

  - name: Write blockdev readahead service
    ansible.builtin.copy:
      force: yes
      dest: "/etc/systemd/system/blockdev-setra.service"
      content: |
        [Unit]
        Description=Set readahead for the hard drive device
        After=local-fs.target

        [Service]
        Type=oneshot
        ExecStart=bash -c '/sbin/blockdev --setra 8192 /dev/sd*'

        [Install]
        WantedBy=multi-user.target

  - name: Write cpufrequtils GOVERNOR
    ansible.builtin.copy:
      force: yes
      dest: /etc/default/cpufrequtils
      mode: 0644
      content: GOVERNOR="performance"

  # - name: enable and restart performance services
  #   ansible.builtin.systemd:
  #     name: "{{item}}"
  #     state: restarted
  #     enabled: true
  #     daemon_reload: true
  #   with_items:
  #   - blockdev-setra
  #   - io-scheduler
  #   - cpufrequtils

  - name: set services dict for handler
    ansible.builtin.set_fact:
      services:
        - { name: 'blockdev-setra', enabled: true, state: 'restarted' }
        - { name: 'io-scheduler', enabled: true, state: 'restarted' }
        - { name: 'cpufrequtils', enabled: true, state: 'restarted' }

  notify:
    - enable_and_restart
