# tasks file for common
---
- name: Common
  become: true
  block:

    - name: Tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ query('fileglob', {{ playbook_dir }}/roles/common/tasks/*.yaml) | reject('main') }}"