- name: Persistent MAC Address
  when: ansible_os_family == 'Linux'
  block:

    - name: systemd-udev MAC link
      ansible.builtin.copy:
        force: true
        dest: "/etc/systemd/network/99-default.link"
        content: |
          [Link]
          NamePolicy=kernel database onboard slot path
          MACAddressPolicy=persistent

    - name: set services dict for handler
      ansible.builtin.set_fact:
        local_services:
          - { name: '99-default.link', enabled: true, state: 'restarted' }

    - name: set services dict for handler
      ansible.builtin.set_fact:
        services: "{{ services + local_services }}"

  notify:
    - enable_and_restart