- name: Linux Syslog
  when: ansible_os_family == 'Linux'
  block:

  - name: drop IPVS no route messages
    ansible.builtin.copy:
      force: true
      dest: "/etc/rsyslog.d/0-drop-ipvs-spam.conf"
      content: |
        :msg, regex, ".*IPVS.*no destination available" ~

  - name: rsyslog remote server
    ansible.builtin.copy:
      force: true
      dest: "/etc/rsyslog.d/99-remote-syslog.conf"
      content: |
        module(load="omprog")
        module(load="mmutf8fix")
        action(type="mmutf8fix" replacementChar="?")
        action(type="omfwd" protocol="tcp" target="{{SYSLOG}}" port="1514" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")

  - name: set services dict for handler
    ansible.builtin.set_fact:
      services:
        - { name: 'rsyslog', enabled: true, state: 'restarted' }

  notify:
    - enable_and_restart