- name: ssh-keys cron
  when: ansible_facts['os_family'] == "Debian"
  block:

    - name: install package
      ansible.builtin.apt:
        update_cache: true
        pkg: ssh-import-id
        state: present

    - name: ssh-keys from github cron
      ansible.builtin.cron:
        name: ssh-import-id-gh bluefishforsale
        minute: "*/15"
        hour: "*"
        weekday: "*"
        user: "{{ ansible_user }}"
        job: ssh-import-id-gh bluefishforsale
        cron_file: "ssh-import-github-keys-bluefishforsale-{{ ansible_user }}"