- name: Linux kernel Sysctl settings
  when: ansible_os_family == 'Linux'
  vars:
    sysctl_vars:
      # allow binding to interfaces not yet up (haproxy/keepalived)
      - net.ipv4.ip_nonlocal_bind: 1
      # don't cache ss-thresh from previous connection
      - net.ipv4.tcp_no_metrics_save: 1
      # Enable Forward Acknowledgment, which operates with Selective Acknowledgment (SACK) to reduce congestion.
      - net.ipv4.tcp_fack: 1
      # recommended default congestion control is htcp
      - net.ipv4.tcp_congestion_control: htcp
      # The maximum number of packets queued in received state
      - net.core.netdev_max_backlog: 30000
      # Enable selective acknowledgment, which improves performance by selectively acknowledging packets received out of order.
      - net.ipv4.tcp_sack: 1
      # Enable calculation of RTT in a more accurate way (see RFC 1323) than the retransmission timeout.
      - net.ipv4.tcp_timestamps: 1
      # If you are using Jumbo Frames, also set this
      - net.ipv4.tcp_mtu_probing: 1
      # Avoid falling back to slow start after a connection goes idle.
      - net.ipv4.tcp_slow_start_after_idle: 0
      # recommended to enable 'fair queueing'
      - net.core.default_qdisc: fq
      # increase TCP max buffer sizes 512MB
      - net.core.rmem_max: 512000000
      - net.core.wmem_max: 512000000
      # Support windows larger than 64KB.
      - net.ipv4.tcp_window_scaling: 1
      # jumbo frames needs probing
      - net.ipv4.tcp_mtu_probing: 1
      # increase Linux autotuning TCP buffer limit
      - net.ipv4.tcp_rmem: 4096 87380 512000000
      - net.ipv4.tcp_wmem: 4096 65536 512000000
      # file watches increase
      - fs.inotify.max_queued_events: 1310720
      - fs.inotify.max_user_instances: 20480
      - fs.inotify.max_user_watches: 655360
      - user.max_inotify_instances: 20480
      - user.max_inotify_watches: 655360
      - kern.maxfiles: 16777216
      - kern.maxfilesperproc: 524288
      # no swapping
      - vm.swappiness: 0
      # ciliumn rp_filter
      # https://github.com/cilium/cilium/issues/10645
      - net.ipv4.conf.lxc*.rp_filter: 0

  block:

    - name: Set Sysctls
      ansible.posix.sysctl:
        sysctl_file: "/etc/sysctl.d/99-z-final-custom-kubecluster-sysctl-tune.conf"
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      with_dict: '{{ sysctl_config }}'
