- name: Unattended Upgrade Cron
  when: ansible_facts['os_family'] == "Debian"
  block:

    - name: install package
      ansible.builtin.apt:
        pkg: unattended-upgrades
        update_cache: true
        state: present

    - name: get ssh-keys from github as cron job
      ansible.builtin.cron:
        name: unattended-upgrade cron
        weekday: "4"
        minute: "30"
        hour: "12"
        user: root
        job: unattended-upgrade
        cron_file: weekly-unattended-upgrade