- name: User tools and configs
  when: ansible_facts['os_family'] == "Debian"
  block:

  - name: Install zsh first
    ansible.builtin.apt:
      pkg: zsh

  - name: Register current username
    ansible.builtin.command: whoami
    register: login_user

  - name: Change user shell to zsh
    ansible.builtin.user:
      name: "{{ login_user.stdout }}"
      ansible.builtin.shell: /bin/zsh

  - name: Mkdir conf & glances
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items:
      - ~/.config
      - ~/.config/glances

  - name: Get ssh-keys from github as cron job
    ansible.builtin.cron:
      name: ssh-import-id-gh {{ github_user_id }}
      weekday: "*"
      minute: "*/15"
      hour: "*"
      user: "{{ login_user.stdout }}"
      job: ssh-import-id-gh {{ github_user_id }}
      cron_file: ssh-import-id-gh-{{ github_user_id }}

  - name: Get oh-my-zsh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/oh-my-zsh-installer.sh
      force: true
      mode: 0755

  - name: Install oh-my-zsh
    ansible.builtin.command: /tmp/oh-my-zsh-installer.sh
    args:
      creates: ~/.oh-my-zsh

  - name: Copy config files
    ansible.builtin.copy:
      force: true
      mode: 0644
      src: '{{ role_path }}/files/{{ item }}'
      dest: ~/{{ item }}
    with_items:
      - .oh-my-zsh/custom/aliases.sh
      - .p10k.zsh
      - .tmux.conf
      - .config/glances/glances.conf


  - name: Install powerlevel10k
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k
      dest: ~/.oh-my-zsh/themes/powerlevel10k
      accept_hostkey: true
      depth: 1

  - name: Set p10k THEME in .zshrc
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      state: present
      backrefs: true
      regexp: '^ZSH_THEME='
      line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

  - name: P10k DISABLE_CONFIGURATION_WIZARD
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      state: present
      line: 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true'

  - name: Clone Ultimate vim config
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k
      dest: ~/.vim_runtime
      accept_hostkey: true
      depth: 1
