---
- hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt: update_cache=yes

    - name: Install a suite of common tools
      apt:
        pkg:
          [ wget, curl, htop, nmap, netcat, strace, strace, fping, bmon, iptraf-ng, apt-transport-https, ca-certificates]

    - name: Add required base users
      user:
        name: terrac
        comment: Terrac Skiens
        shell: /bin/zsh
        uid: 11010
        group: sudo
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Authorized Keys for terrac
      authorized_key:
        user: terrac
        state: present
        key: https://github.com/bluefishforsale.keys

    - name: Virtualization software
      apt:
        state: present
        pkg:
          [ qemu ]
