[virtualbox]
virtual.local  ansible_connection=ssh        ansible_user=terrac

[pi]
192.168.1.2 ansible_connection=ssh  ansible_user=ubuntu

[up2]
node000.local ansible_connection=ssh  ansible_user=ubuntu
node001.local ansible_connection=ssh  ansible_user=ubuntu
node002.local ansible_connection=ssh  ansible_user=ubuntu
node003.local ansible_connection=ssh  ansible_user=ubuntu
