[local]
127.0.0.1 ansible_connection=local

[pi]
192.168.1.2 ansible_connection=ssh  ansible_user=ubuntu

[dns]
192.168.1.2 ansible_connection=ssh  ansible_user=ubuntu

[k8s]
node[000:004].home ansible_connection=ssh  ansible_user=ubuntu

[k8s_worker]
node000.home ansible_connection=ssh  ansible_user=ubuntu
node004.home ansible_connection=ssh  ansible_user=ubuntu


[k8s_controller]
node[001:003].home ansible_connection=ssh  ansible_user=ubuntu

[etcd]
node[001:003].home ansible_connection=ssh  ansible_user=ubuntu
