- name: KIND clusters
  hosts: all
  tasks:

  - name: kind installed and in $PATH
    shell: which kind
    register: kind_installed

  - name: KIND clusters
    when: kind_installed.rc == 0
    block:
    - name: consul kind cluster config
      ansible.builtin.set_fact:
        consul_config: |
          ---
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            kubeadmConfigPatches:
            - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "ingress-ready=true"
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP

    - name: consul_connect cluster
      command: kind create cluster --name=consul --config=-"{{ consul_config }}"