- name: KIND clusters
  hosts: all
  vars:
    kind_types:
    - consul
    - istio
    - linkerd
  tasks:
    - name: Make KIND for each type of software
      include_tasks: kind_subtask.yaml
      loop: "{{ kind_types }}"