- name: nuke kubernetes, ceph, and containers.
  ignore_errors: yes
  hosts: k8s
  become: yes
  tasks:
  - name: nuke pass 1
    include: "./subtask_nuke.yaml"

  - name: reboot hosts
    shell: reboot

  - name: Wait 15 mins seconds, but only start checking after 60 seconds
    ansible.builtin.wait_for_connection:
      delay: 60
      timeout: 900

  - name: nuke pass 2
    include: "./subtask_nuke.yaml"

  - name: reboot hosts
    shell: reboot

  - name: Wait 15 mins seconds, but only start checking after 60 seconds
    ansible.builtin.wait_for_connection:
      delay: 60
      timeout: 900