---
- name: Loop over all users and call user_template playbook
  hosts: all
  vars_files:
    - vars_users.yaml
  vars:
    github: bluefishforsale

  tasks:
    - name: install zsh first
      become: true
      apt:
        pkg: [ zsh, git ]

    - name: Shell, Theme, and config for logged in user
      block:
      - name: get oh-my-zsh
        get_url:
          url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
          dest: /tmp/oh-my-zsh-installer.sh
          force: true
          mode: 0755

      - name: install oh-my-zsh
        shell: /tmp/oh-my-zsh-installer.sh
        args:
          creates: ~/.oh-my-zsh

      - name: copy aliases into custom zsh dir
        copy:
          force: yes
          src: files/shell/aliases.sh
          dest: ~/.oh-my-zsh/custom/

      - name: register logged in username
        set_fact:
          login_user: "{{ansible_user_id}}"

      - name: Change user shell to zsh
        become: true
        user:
          name: "{{login_user}}"
          shell: /bin/zsh

      - name: install powerlevel10k
        git:
          repo: https://github.com/romkatv/powerlevel10k
          dest: ~/.oh-my-zsh/themes/powerlevel10k
          accept_hostkey: yes
          force: yes
          depth: 1

      - name: Set p10k THEME in .zshrc
        lineinfile:
          path: ~/.zshrc
          state: present
          backrefs: yes
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

      - name: p10k config file
        copy:
          force: yes
          src: files/shell/p10k.zsh
          dest: ~/.p10k.zsh"

      - name: P10k DISABLE_CONFIGURATION_WIZARD
        lineinfile:
          path: ~/.zshrc
          state: present
          line: 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true'

      - name: ultimate vim
        shell:
          cmd: git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
        args:
          creates: ~/.vim_runtime

      - name: tmux conf
        copy:
          force: yes
          src: files/shell/tmux.conf
          dest: ~/.tmux.conf

      - name: mkdir conf & glances
        file:
          path: "{{item}}"
          state: directory
        with_items:
        - ~/.config
        - ~/.config/glances

      - name: Glances conf
        copy:
          force: yes
          src: files/shell/glances.conf
          dest: ~/.config/glances/glances.conf

    ################ Root user ###################
    - name: Stuff done for root
      become: yes

      block:
      - name: Add github keys to user
        authorized_key:
          user: root
          state: present
          key: "https://github.com/{{github}}.keys"

      - name: Passwordless sudo for 'sudo' group
        lineinfile:
          path: /etc/sudoers
          state: present
          regexp: '^%sudo'
          line: '%sudo ALL=(ALL) NOPASSWD: ALL'

      - name: get oh-my-zsh
        get_url:
          url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
          dest: /tmp/oh-my-zsh-installer.sh
          force: true
          mode: 0755

      - name: Root install oh-my-zsh
        shell: /tmp/oh-my-zsh-installer.sh
        args:
          creates: /root/.oh-my-zsh

      - name: Root Change user shell to zsh
        user:
          name: root
          shell: /bin/zsh

      - name: Root install powerlevel10k
        git:
          repo: https://github.com/romkatv/powerlevel10k
          dest: /root/.oh-my-zsh/themes/powerlevel10k
          accept_hostkey: yes
          force: yes
          depth: 1

      - name: Root Set p10k THEME in .zshrc
        lineinfile:
          path: /root/.zshrc
          state: present
          backrefs: yes
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

      - name: Root p10k config file
        copy:
          force: yes
          src: files/shell/p10k.zsh
          dest: /root/.p10k.zsh

      - name: Root P10k DISABLE_CONFIGURATION_WIZARD
        lineinfile:
          path: /root/.zshrc
          state: present
          line: 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true'

      - name: Root ultimate vim
        shell:
          cmd: git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
        args:
          creates: /root/.vim_runtime

      - name: Root tmux conf
        copy:
          force: yes
          src: files/shell/tmux.conf
          dest: /root/.tmux.conf

      - name: Root mkdir conf & glances
        file:
          path: "{{item}}"
          state: directory
        with_items:
        - /root/.config
        - /root/.config/glances

      - name: Root Glances conf
        copy:
          force: yes
          src: files/shell/glances.conf
          dest: ~/.config/glances/glances.conf

      - name: add users
        include_tasks: subtask_user.yaml
        loop: "{{ user }}"
