
- name: Kube 09 cilium
  hosts: k8s
  strategy: linear
  gather_facts: false
  become: true
  vars_files:
    - vars_kube.yaml

  tasks:
    - name: Download {{ cilium_repo }} {{ cilium_version }}
      block:

        - name: Create tempdir
          ansible.builtin.tempfile:
            state: directory
            suffix: _dwnld
          register: tempfolder_1

        - name: Installing {{ cilium_repo }} {{ cilium_version }}
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ cilium_project_url }}"
            dest: "{{ tempfolder_1.path }}"
            keep_newer: true
            extra_opts:
              - --strip=1
              - --no-anchored

        - name: Register files to mv
          ansible.builtin.find:
            paths: "{{ tempfolder_1.path }}"
            patterns: "cilium*"
          register: cilium_files

        - name: Mv files to bindir
          ansible.builtin.copy:
            remote_src: true
            src: "{{ item.path }}"
            dest: "{{ cilium_binpath }}/{{ item.path | basename }}-{{ cilium_version }}"
            mode: "0755"
          with_items: "{{ cilium_files.files }}"

        - name: Ln files to bindir
          ansible.builtin.file:
            state: link
            force: true
            src: "{{ cilium_binpath }}/{{ item.path | basename }}-{{ cilium_version }}"
            dest: "{{ cilium_binpath }}/{{ item.path | basename }}"
          with_items: "{{ cilium_files.files }}"

        - name: Rm tempdir
          ansible.builtin.file:
            state: absent
            path: "{{ tempfolder_1.path }}"
