- name: Dist certs to kube contollers
  hosts: k8s_controller
  strategy: linear
  become: yes
  vars_files:
    - vars_kube.yaml

  tasks:
  - name: Distribute the Certs made in previous steps
    block:

    - name: Make The Kube Certs Dir (controller)
      file:
        path: "{{ k8s_dir }}"
        mode: 0755
        owner: root
        group: root
        state: directory

    - name: Copy PEM and Keys (controller)
      copy:
        force: yes
        dest: "{{ k8s_dir }}/{{ item }}"
        src: "files/cfssl/{{item}}"
        mode: 0644
        group: root
        owner: root
      with_items:
        - admin.pem
        - admin-key.pem
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
        - kube-aggregator.pem
        - kube-aggregator-key.pem
        - "{{inventory_hostname}}-key.pem"
        - "{{inventory_hostname}}.pem"
