---
- name: root and system level
  hosts: all
  vars:
    dummy: Null

  tasks:
  - name: bind and other packages
    become: yes
    block:

    - name: apt-get update
      apt: update_cache=yes

    - name: bind and tools
      apt:
        pkg:
          [ isc-dhcp-server, bind9, bind9utils, dnsutils]

    - name: rndc-key-check
      shell: cat /etc/bind/rndc.key
      register: rndc_keyfile

    - name: rndc-key-write
      when: rndc_keyfile.stdout | length > 0
      shell: rndc-confgen -a -b 512

    - name: configs
      copy:
        src: bind9/{{ item  }}
        dest: /etc/bind/{{ item  }}
        owner: bind
        group: bind
        mode: 0644
      with_items:
        - named.conf.local
        - named.conf.options

    - name: make conf dirs
      file:
        path: /var/lib/bind/
        state: directory
        owner: bind
        group: bind
        mode: 0755

    - name: zones
      copy:
        src: bind9/{{ item  }}
        dest:  /var/lib/bind/{{ item  }}
        owner: bind
        group: bind
        mode: 0644
      with_items:
        - local.zone
        - db.rev.1.168.192.in-addr.arpa

    - name: Config Check
      shell: named-checkconf


  - name: restart bind9
    shell: systemctl restart bind9