- name: proxmox vm setup
  become: yes
  hosts: all
  tasks:

  - name: disable eth0 dhcp
    ansible.builtin.lineinfile:
      path: /etc/network/interfaces
      state: present
      backrefs: true
      regexp: '^(iface eth0 inet dhcp)$'
      line: '#\g<1>'

  - name: install some proxmox packages
    apt:
      update_cache: true
      force_apt_get: true
      allow-unauthenticated: true
      pkg:
      - qemu-guest-agent

  - name: install some proxmox packages
    apt:
      upgrade: full
