---
- name: root and system level
  hosts: all
  vars:
    foo: bar

  tasks:
  - name: Tools and Utilities
    become: yes
    block:

    - name: mkdir /tmp/perc_cli
      file:
        path: "/tmp/perc_cli"
        mode: 0777
        owner: root
        group: root
        state: directory

    - name: PercCLI Download and unpack directly from HTTP source
      unarchive:
        src: https://dl.dell.com/FOLDER04470715M/1/perccli_7.1-007.0127_linux.tar.gz
        dest: "/tmp/perc_cli"
        copy: no

    - name: Enable universe repository
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
        - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

    - name: Update repositories cache
      apt:
        name: alien
        update_cache: yes

    - name: Convert RPM to deb
      shell:
        chdir: /tmp/perc_cli/Linux
        cmd: alien perccli-007.0127.0000.0000-1.noarch.rpm

    - name: Install Perc CLI
      apt:
        deb: /tmp/perc_cli/Linux/perccli_007.0127.0000.0000-2_all.deb

    - name: Symlink perccli to /usr/local/bin
      file:
        src: /opt/MegaRAID/perccli/perccli64
        dest: /usr/local/bin/perccli64
        state: link

    - name: intel x520-DA2 download
      unarchive:
        remote_src: yes
        src: https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.12.5/ixgbe-5.12.5.tar.gz/download
        dest: /tmp/

    - name: intel x520-DA2 package setup
      shell: >
        cd /tmp/ixgbe-5.12.5
        make install

    - name: load the module
      shell: >
        modprobe ixgbe

    - name: intel x520-DA2 modules file
      copy:
        force: yes
        dest: "/etc/modules-load.d/ixgbe"
        content: |
          ixgbe

    - name: netplan for 10G bonded
      copy:
        force: yes
        dest: "/etc/netplan/05-10G-bonding.yaml"
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp65s0f0:
                dhcp4: false
                dhcp6: false
              enp65s0f1:
                dhcp4: false
                dhcp6: false
            bonds:
              bond0:
                interfaces:
                  - enp65s0f0
                  - enp65s0f1
                addresses: ["{{lookup('community.general.dig', inventory_hostname)}}/24"]
                gateway4: 192.168.1.1
                nameservers:
                  addresses: [192.168.1.2]
                dhcp4: false
                dhcp6: false
                parameters:
                  mode: 802.3ad
                  lacp-rate: fast
                  mii-monitor-interval: 100
                  transmit-hash-policy: layer2+3

    - name: netplan apply
      shell: >
        netplan apply