---
- name: root and system level
  hosts: all
  tasks:
  - name: Seconds since last apt-get update
    shell: echo $(($(date +"%s") - $(stat -c %Y /var/cache/apt/)))
    register: apt_get_update_secs

  - name: base packages
    become: yes
    block:
    - name: apt-get update
      # when: apt_get_update_secs.stdout|int > 1800
      apt: update_cache=yes

    - name: Install a suite of common tools
      apt:
        pkg:
          [ zsh, wget, curl, htop, nmap, netcat, strace, fping, bmon, iptraf-ng, tmux, glances, unzip]