- name: Kube 07 etcd
  hosts: etcd
  strategy: linear
  become: true
  vars_files:
    - vars_kube.yaml

  tasks:
  - name: Directories
    block:

    - name: MKdir "{{ etcd_confpath }}"
      ansible.builtin.file:
        path: "{{ etcd_confpath }}"
        state: directory
        mode: "0755"
      with_items: ["{{ etcd_confpath }}", "{{ etcd_datapath }}"]

    - name: create tempdir
      ansible.builtin.tempfile:
        state: directory
        suffix: _dwnld
      register: tempfolder_1

    - name: Copy certs for etcd
      ansible.builtin.copy:
        force: true
        src: "files/cfssl/{{item}}"
        dest: "{{etcd_confpath}}/{{item}}"
        mode: 0755
      with_items:
      - ca.pem
      - kubernetes-key.pem
      - kubernetes.pem

    - name: Download "{{etcd_repo}} "{{etcd_version}}"
      block:

      - name: installing "{{ etcd_repo }} {{etcd_version}}"
        ansible.builtin.unarchive:
          remote_src: true
          src: "{{ etcd_project_url }}"
          dest: "{{ tempfolder_1.path }}"
          keep_newer: true
          extra_opts:
          - --strip=1
          - --no-anchored

      - name: mv files to bindir
        ansible.builtin.find:
          paths: "{{ tempfolder_1.path }}"
          patterns: "etcd*"
        register: etcd_files

      - name: Mv files to bindir
        ansible.builtin.copy:
          remote_src: true
          src: "{{ item.path }}"
          dest: "{{ etcd_binpath }}/{{ item.path | basename }}-{{ etcd_version }}"
          mode: "0755"
        with_items: "{{ etcd_files.files }}"

      - name: Ln files to bindir
        ansible.builtin.file:
          state: link
          force: true
          src: "{{ etcd_binpath }}/{{ item.path | basename }}-{{ etcd_version }}"
          dest: "{{ etcd_binpath }}/{{ item.path | basename }}"
        with_items: "{{ etcd_files.files }}"

      - name: Rm tempdir
        ansible.builtin.file:
          state: absent
          path: "{{tempfolder_1.path}}"

    - name: Make EtcD systemd service
      block:
      - name: Get IP for a subset of hosts, store in HOST_IP
        ansible.builtin.set_fact:
          HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
        loop: "{{ groups['etcd'] }}"

      - name: Flatten dict to formatted string, store PEERS_MAP
        ansible.builtin.set_fact:
          PEERS_MAP: "{{ PEERS_MAP }}{{ (index > 0) | ternary(',','') }}{{ item.key }}=https://{{ item.value }}:2380"
        loop: "{{  HOST_IP | dict2items }}"
        loop_control:
          index_var: index

      # Create the config file from template
      - name: systemd Unit file copy to target
        ansible.builtin.copy:
          force: true
          dest: /etc/systemd/system/etcd.service
          content: '{{ lookup("template", "files/etcd/etcd.service.j2") }}'
          mode: 0644
          group: root
          owner: root

      - name: enable and restart etcd service
        ansible.builtin.systemd:
          name: etcd
          state: restarted
          enabled: true
          daemon_reload: true
