- name: 10g bonded Network
  hosts: all

  tasks:
  - name: register interfaces carrier
    ansible.builtin.shell: |
      grep -l 1 /sys/class/net/e*/carrier | xargs -n1 dirname | xargs -n1 basename
    register: carrier_up

  - name: register interfaces speeds
    ansible.builtin.shell: |
      grep -v -- -1 /sys/class/net/e*/speed | sed -e 's/\// /g'
    register: iface_speed

  # - name: netplan for 10G bonded
  #   copy:
  #     force: yes
  #     dest: "/etc/netplan/05-10G-bonding.yaml"
  #     content: '{{ lookup("template", "files/netplan/05-10G-bonding.yaml.j2") }}'

  # - name: remove default netplan config
  #   ignore_errors: yes
  #   file:
  #     path: /etc/netplan/00-installer-config.yaml
  #     state: absent

  # - name: netplan apply
  #   ansible.builtin.shell: >
  #     netplan apply

  - name: 10g tc qdisc boot oneshot service
    copy:
      dest: /etc/systemd/system/10g_qdisc.service
      content: |
        [Unit]
        After=network.target

        [Install]
        WantedBy=multi-user.target

        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/sbin/tc qdisc add dev eno1 root fq maxrate 9gbit
        ExecStart=/sbin/tc qdisc add dev eno2 root fq maxrate 9gbit
        ExecStart=/sbin/tc qdisc add dev eno3 root fq maxrate 9gbit
        ExecStart=/sbin/tc qdisc add dev eno4 root fq maxrate 9gbit

  - name: Enable and Start service
    systemd:
      enabled: yes
      state: restarted
      name: 10g_qdisc.service
      daemon_reload: true
