- name: Kube 08 node kubectl admin
  hosts: k8s
  strategy: linear
  vars_files:
    - vars_kube.yaml

  tasks:
  - name: Remote node configure for local kubectl admin access
    ansible.builtin.shell: >-
      kubectl config set-cluster k8s \
        --certificate-authority=/var/lib/kubernetes/ca.pem \
        --embed-certs=true \
        --server=https://192.168.1.99:6443
      kubectl config set-credentials admin \
        --client-certificate=/var/lib/kubernetes/admin.pem \
        --client-key=/var/lib/kubernetes/admin-key.pem
      kubectl config set-context k8s \
        --cluster=k8s \
        --user=admin
      kubectl config use-context k8s
