- name: Dist Kubeconfigs to kube workers
  hosts: k8s
  strategy: linear
  become: yes
  vars_files:
    - vars_kube.yaml

  tasks:
  - name: Distribute the files made in previous steps
    block:

    - name: Ensure we have a directory to place files
      file:
        path: "{{ k8s_dir }}"
        mode: 0755
        owner: root
        group: root
        state: directory

    - name: Copy proxy and instance kubeconfig
      copy:
        force: yes
        dest: "{{ k8s_dir }}/{{ item }}"
        src: "files/kubeconf/{{item}}"
        mode: 0644
        group: root
        owner: root
      with_items:
        - "kube-proxy.kubeconfig"
        - "{{inventory_hostname}}.kubeconfig"