---
- name: Loop over all users and call user_template playbook
  hosts: all
  vars_files:
    - vars_users.yaml
  vars:
    github: bluefishforsale
  tasks:
    - name: Global oh-my-zsh shell, theme, and vimrc
      become: yes
      block:

      - name: Add github keys to Root
        authorized_key:
          user: root
          state: present
          key: "https://github.com/{{github}}.keys"

      - name: Sudo group gets passwordless sudo access
        lineinfile:
          path: /etc/sudoers
          state: present
          regexp: '^%sudo'
          line: '%sudo ALL=(ALL) NOPASSWD: ALL'

      - name: install oh my zsh as root
        shell:
          cmd: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -
          creates: /root/.oh-my-zsh

      - name: move oh-my-zsh to /usr/share
        shell:
          cmd: mv /root/.oh-my-zsh /usr/share/oh-my-zsh
          creates: /root/.oh-my-zsh

      - name: copy zshrc template
        shell:
          cmd: cp /usr/share/oh-my-zsh/templates/zshrc.zsh-template /usr/share/oh-my-zsh/zshrc
          creates: /root/.oh-my-zsh

      - name: /etc/skel zshrc symlink
        shell:
          cmd: ln /usr/share/oh-my-zsh/zshrc /etc/skel/.zshrc
          creates:  /etc/skel/.zshrc

      - name: install powerlevel10k
        git:
          repo: https://gitee.com/romkatv/powerlevel10k.git
          dest: /usr/share/oh-my-zsh/custom/themes/powerlevel10k
          accept_hostkey: yes
          force: yes
          depth: 1

      - name: Set p10k THEME in .zshrc
        lineinfile:
          path: /etc/skel/.zshrc
          state: present
          backrefs: yes
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

      - name: p10k config and state
        copy:
          src: files/p10k.zsh
          dest: /etc/skel/.p10k.zsh

      - name: ultimate vim
        shell:
          cmd: "{{ local_item }}"
          creates: /etc/skel/.vim_runtime
        with_items:
          - git clone --depth=1 https://github.com/amix/vimrc.git /etc/skel/.vim_runtime
          - mkdir -p /usr/share/vim_runtime
          - cmod -R 1755 /usr/share/vim_runtime
          - sh /tmp/.vim_runtime/install_awesome_vimrc.shsh /etc/skel/.vim_runtime/install_awesome_vimrc.sh
          - cp -rp /root/.vimrc /etc/skel
        loop_control:
          loop_var: local_item

      # - name: tmux conf
      #   copy:
      #     src: files/tmux.conf
      #     dest: ~"{{ user.name }}"/.tmux.conf
      #   loop: "{{ user }}"

      # - name: Ensures /etc/skel/.config/glances path exists
      #   file: path=/etc/skel/.config/glances state=directory

      # - name: Glances conf
      #   copy:
      #     src: files/glances.conf
      #     dest: /etc/skel/.config/glances/glances.conf

      # - name: add each user one at a time with some custom setup
      #   include_tasks: subtask_user.yaml
      #   loop: "{{ user }}"
