# - name: bnx2x Network
#   hosts: all

#   tasks:
#   - name:  Network driver, netplan and tuning specific to interfaces
#     when: bnx2x_nic is defined
#     become: yes
#     block:

    # - name: netplan for bnx2x 10G bonded
    #   copy:
    #     force: yes
    #     dest: "/etc/netplan/05-10G-bonding.yaml"
    #     content: |
    #       network:
    #         version: 2
    #         renderer: networkd
    #         ethernets:
    #           eth0:
    #             mtu: 8192
    #             dhcp4: false
    #             dhcp6: false
    #           eth1:
    #             mtu: 8192
    #             dhcp4: false
    #             dhcp6: false
    #         bonds:
    #           bond0:
    #             mtu: 8192
    #             interfaces:
    #               - eth0
    #               - eth1
    #             addresses: ["{{lookup('community.general.dig', inventory_hostname)}}/24"]
    #             routes:
    #               - to: default
    #                 via: 192.168.1.1
    #             nameservers:
    #               addresses: [192.168.1.2]
    #               search: [home, local]
    #             dhcp4: false
    #             dhcp6: false
    #             parameters:
    #               mode: 802.3ad
    #               lacp-rate: slow
    #               mii-monitor-interval: 500ms
    #               fail-over-mac-policy: follow
    #               transmit-hash-policy: layer3+4

    # - name: remove default netplan config
    #   file:
    #     path: /etc/netplan/00-installer-config.yaml
    #     state: absent

    # - name: netplan apply
    #   ansible.builtin.shell: >
    #     netplan apply
