---
- name: Bind9
  hosts: dns

  tasks:
  - name: bind and other packages
    become: yes
    block:

    - name: Handle dpkg locks and repair
      include_tasks: subtask_fix_dpkg_lock.yaml

    - name: apt-get update
      apt: update_cache=yes

    - name: bind and tools
      apt:
        pkg:
          [ bind9, bind9utils, dnsutils]

    - name: rndc-key-write
      ansible.builtin.shell:
        creates: /etc/bind/rndc.key
        cmd: rndc-confgen -a -b 512

    - name: configs
      copy:
        force: yes
        src: bind9/{{ item  }}
        dest: /etc/bind/{{ item  }}
        owner: bind
        group: bind
        mode: 0644
      with_items:
        - named.conf.local
        - named.conf.options

    - name: make conf dirs
      file:
        path: /var/lib/bind/
        state: directory
        owner: bind
        group: bind
        mode: 0755

    # - name: zones
    #   copy:
    #     force: yes
    #     src: bind9/{{ item  }}
    #     dest:  /var/lib/bind/{{ item  }}
    #     owner: bind
    #     group: bind
    #     mode: 0644
    #   with_items:
    #     - cluster.local.zone
    #     - home.zone
    #     - db.rev.1.168.192.in-addr.arpa

    - name: write zone templates
      copy:
        force: yes
        dest: "/var/lib/bind/{{item}}"
        content: '{{ lookup("template", "files/bind9/{{item}}.j2") }}'
        mode: 0644
        owner: bind
        group: bind
      with_items:
        - home.zone
        - cluster.local.zone
        - db.rev.1.168.192.in-addr.arpa

    - name: Config Check
      ansible.builtin.shell: named-checkconf

    - name: Check home zone
      ansible.builtin.shell: named-checkzone  home /var/lib/bind/home.zone

    - name: Check reverse mapping zone
      ansible.builtin.shell: named-checkzone 1.168.192.in-addr.arpa /var/lib/bind/db.rev.1.168.192.in-addr.arpa

    # - name: remove the jnl files before restart
    #   ansible.builtin.shell: find /var/lib/bind -type f -name "*.jnl" -delete

    - name: Create systemd override directory for named.service
      file:
        path: /etc/systemd/system/named.service.d
        state: directory
        mode: '0755'

    - name: Add systemd override for named.service
      copy:
        dest: /etc/systemd/system/named.service.d/override.conf
        content: |
          [Service]
          # Run this command before each attempt to start the service
          ExecStartPre=/usr/bin/find /var/lib/bind -type f -name "*.jnl" -delete

          # Clear the existing ExecStart (required if redefining it)
          ExecStart=
          ExecStart=/usr/sbin/named -f -u bind

          # Always restart the service on failure
          Restart=always

          # No limit on how many times it will restart
          StartLimitIntervalSec=0
          StartLimitBurst=0

          # 10 second delay between restart attempts
          RestartSec=10

    - name: Ensure correct permissions for the override file
      file:
        path: /etc/systemd/system/named.service.d/override.conf
        mode: '0644'

    - name: Enable and Start service
      systemd:
        enabled: yes
        state: restarted
        name: named
        daemon_reload: true
