---
- name: root and system level
  hosts: all
  tasks:
  - name: Seconds since last apt-get update
    shell: echo $(($(date +"%s") - $(stat -c %Y /var/cache/apt/)))
    register: apt_get_update_secs

  - name: base packages
    become: yes
    block:
    - name: apt-get update
      when: apt_get_update_secs.stdout|int > 1800
      apt: update_cache=yes

    - name: Install a suite of common tools
      apt:
        pkg:
          [ zsh, wget, curl, htop, nmap, netcat, strace, fping, bmon, iptraf-ng, tmux ]

    - name: Virtualization software
      apt:
        state: present
        pkg:
          [ qemu ]

  - name: docker.io
    become: yes
    block:
      - name: packages needed to get started
        apt:
          state: present
          pkg:
            [ apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common ]

      - name: add the docker apt-key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg

      - name: adding the repo
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
          state: present

      - name: apt-get update
        apt: update_cache=yes

      - name: docker packages
        apt:
          state: present
          pkg:
            [ docker-ce, docker-ce-cli, containerd.io ]

      - name: test docker run
        command: "{{ item }}"
        with_items:
        - docker run --rm hello-world

      - name: install KIND
        get_url:
          url: https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
          dest: /usr/local/bin/kind

      - name: KIND exec perms
        file:
          path: /usr/local/bin/kind
          state: touch
          mode: 0755

      - name: Download K9s
        get_url:
          url: https://github.com/derailed/k9s/releases/download/v0.24.2/k9s_Linux_x86_64.tar.gz
          dest: /tmp/k9s.tgz

      - name: k9s untar
        command: tar -xf /tmp/k9s.tgz -C /usr/local/bin/ --mode=0755

  - name: enable and start all services
    become: yes
    systemd:
      enabled: yes
      state: started
      name: docker
    systemd:
      enabled: yes
      state: started
      name: ssh