- name: root and system level
  become: yes
  hosts: all
  vars_files:
    - vars_kube.yaml
  vars:
    new_paths: '/usr/local/go/bin'

  tasks:
  - name: Stop snapd
    systemd:
      state: stopped
      name: snapd
      enabled: false
      daemon_reload: true

  - name: apt-get update
    apt: update_cache=yes

  - name: Install a suite of common tools
    apt:
      pkg:
        [
          golang, gcc, zsh, wget, curl, htop, sysstat, iotop, iperf3, impitool,
          nmap, make, netcat, strace, fping, bmon, jq, iptraf-ng, tmux,
          glances, unzip, ntpdate, net-tools, lvm2
        ]

  - name: old_paths
    shell: awk -F \= '{print $2}' /etc/environment | sed -e 's/\:/\n/g' | sort -u | sed -e 's/\"//g' | xargs | sed -e 's/\ /:/g'
    register: old_paths

  - name: add go to the environment PATH
    lineinfile:
      path: /etc/environment
      state: present
      backrefs: yes
      regexp: '^PATH=.*'
      line: 'PATH={{ old_paths.stdout }}:{{ new_paths }}'

  - name: Set the Host TZ and hwclock to UTC
    community.general.timezone:
      hwclock: UTC
      name: UTC

  - name: copy ntpdate cron
    copy:
      force: yes
      src: files/crons/ntpdate.cron
      dest: /etc/cron.d/cron.ntpdate
      owner: root
      group: root
      mode: 0644

  - name: set time and date from NTP upstream
    shell: /usr/sbin/ntpdate time.nist.gov

  - name: rsyslog remote server
    copy:
      force: yes
      dest: "/etc/rsyslog.d/99-remote-syslog.conf"
      content: |
        module(load="omprog")
        module(load="mmutf8fix")
        action(type="mmutf8fix" replacementChar="?")
        action(type="omfwd" protocol="tcp" target="{{SYSLOG}}" port="1514" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")

  - name: reload rsyslog
    systemd:
      name: rsyslog
      state: restarted
      enabled: true
      daemon_reload: true

  - name: Sysctl Network Tunings
    copy:
      dest: "/etc/sysctl.d/00-10g-network-tunings.conf"
      content: |
        # open files and inodes
        fs.inotify.max_user_instances = 1024
        # don't cache ssthresh from previous connection
        net.ipv4.tcp_no_metrics_save = 1
        # recommended default congestion control is htcp
        net.ipv4.tcp_congestion_control = htcp
        # If you are using Jumbo Frames, also set this
        net.ipv4.tcp_mtu_probing = 1
        # recommended to enable 'fair queueing'
        net.core.default_qdisc = fq
        # increase TCP max buffer size setable using setsockopt()
        net.core.rmem_max = 536870912
        net.core.wmem_max = 536870912
        # increase Linux autotuning TCP buffer limit
        net.ipv4.tcp_rmem = 4096 87380 268435456
        net.ipv4.tcp_wmem = 4096 65536 268435456

  - name: sysctl reload
    shell: sysctl --system