- name: APIserver CRB
  hosts: k8s_controller
  strategy: free
  become: yes
  vars_files:
    - vars_kube.yaml
  tasks:
  - name: "Copy over kube-apiserver-to-kubelet.yaml"
    copy:
      force: yes
      dest: "{{pki_dir}}/kube-apiserver-to-kubelet.yaml"
      src: "files/kubelet/kube-apiserver-to-kubelet.yaml"

  - name: Create the system:kube-apiserver-to-kubelet ClusterRole / ClusterRoleBinding
    ignore_errors: true
    ansible.builtin.shell:
      cmd: kubectl apply --kubeconfig "{{pki_dir}}/admin.kubeconfig" -f "{{pki_dir}}/kube-apiserver-to-kubelet.yaml"
