# HARD YOLO without any package versioning... YMMV
# the time of writing this was tested on debian12 bookwork cloud-init EFI image
- name: Nvidia Driver, encoding patch, and Containerd config
  hosts: all
  vars_files:
    - vars_kube.yaml

  tasks:
    - name: Driver and Patch
      become: true
      when: nvidia_gpu is defined

      block:
      - name: Stop containerd / kubelet
        ansible.builtin.systemd:
          state: stopped
          name: "{{ item }}"
        ignore_errors: true
        with_items:
          - containerd
          - kubelet

      - name: Blacklist the nuevo driver
        ansible.builtin.copy:
          dest: /etc/modprobe.d/blacklist-nvidia-nouveau.conf
          content: |
            blacklist nouveau
            options nouveau modeset=0
          force: yes
          mode: 0644
          group: root
          owner: root

      - name: Remove the nuevo module
        ansible.builtin.command: rmmod nuevo
        ignore_errors: true

      - name: Nvidia GPG key
        ansible.builtin.get_url:
          url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
          dest: /usr/share/keyrings/nvidia-container-runtime.gpg

      - name: Debian non-free repo
        ansible.builtin.apt_repository:
          filename: deb-nonfree.list
          repo: deb http://deb.debian.org/debian/ bookworm main non-free-firmware contrib non-free
          state: present

      - name: Nvidia container runtime repo
        # use copy here becuase multi-line was getting concat by apt_repo
        ansible.builtin.copy:
          dest: /etc/apt/sources.list.d/nvidia-container-runtime.list
          content: |
            deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
            deb https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH) /

      - name: Set kernel version
        register: kernel_version
        ansible.builtin.shell:
          cmd: uname -r

      - name: Apt install packages
        ansible.builtin.apt:
          update_cache: true
          pkg: "{{ item }}"
        with_items:
        - "linux-headers-{{kernel_version.stdout}}"
        - dkms
        - nvidia-driver
        - firmware-misc-nonfree
        - nvidia-container-runtime

      - name: Clone the Git Repository
        git:
          repo: https://github.com/keylase/nvidia-patch.git
          dest: "{{ ansible_env.HOME }}/nvidia-patch"


      - name: Install keylase patch
        register: kernel_version
        ansible.builtin.shell:
          cmd: sh -c ./patch.sh
          chdir: "{{ ansible_env.HOME }}/nvidia-patch"

      - name: Test the host nvidia-smi
        ignore_errors: true
        ansible.builtin.shell:
          cmd: nvidia-smi

      - name: Write Containerd config
        ansible.builtin.shell:
          cmd: containerd config default > /etc/containerd/config.toml

      - name: Containerd Runtime change to nvidia-container-runtime
        ansible.builtin.lineinfile:
          path: /etc/containerd/config.toml
          state: present
          backrefs: true
          regexp: '(\ +)runtime = "runc"'
          line: '\g<1>runtime = "nvidia-container-runtime"'

      - name: Update init ramfs
        ansible.builtin.shell:
          cmd: update-initramfs -u

      - name: Reboot target to really get changes
        reboot:
          reboot_timeout: 300

