- name: Kube 05.1 Gen Kubeconfigs
  hosts: local
  vars_files:
    - vars_kube.yaml

  tasks:
  - name: Every Kube Needs a Config
    block:

    - name: Worker Configs
      ansible.builtin.include_tasks: "./subtask_kubeconfig_node.yaml"
      with_inventory_hostnames:
        - k8s

    - name: Kube-Proxy Config
      ansible.builtin.include_tasks: "./subtask_kubeconfig_proxy.yaml"
      with_items:
        - "kube-proxy"

    - name: Kube-Controller-Manager Config
      ansible.builtin.include_tasks: "./subtask_kubeconfig_controller_mgr.yaml"
      with_items:
        - "kube-controller-manager"

    - name: Kube-Scheduler Config
      ansible.builtin.include_tasks: "./subtask_kubeconfig_kube_scheduler.yaml"
      with_items:
        - "kube-scheduler"

    - name: Kube-Admin User Config
      ansible.builtin.include_tasks: "./subtask_kubeconfig_kube_admin.yaml"
      with_items:
        - "admin"