- name: Dist Encryption Config to kube controllers
  hosts: k8s_controller
  strategy: linear
  become: yes
  vars_files:
    - vars_kube.yaml

  tasks:
    - name: Copy Key To Controllers
      copy:
        force: yes
        dest: "{{k8s_dir}}/{{item}}"
        content: '{{ lookup("template", "files/kube_encryption_conf/{{item}}.j2") }}'
        mode: 0644
        group: root
        owner: root
      with_items:
        - encryption-config.yaml