- name: Kube 04.2 Dist PKI Workers
  hosts: k8s
  become: yes
  vars_files:
    - vars_kube.yaml
  tasks:
  - name: Distribute the Certs made in previous steps
    block:

    - name: Make The Kube Certs Dir (workers)
      file:
        path: "{{ pki_dir }}"
        mode: 0755
        owner: root
        group: root
        state: directory

    - name: Copy PEM and Keys (workers)
      copy:
        force: yes
        dest: "{{ pki_dir }}/{{ item }}"
        src: "files/cfssl/{{item}}"
        mode: 0644
        group: root
        owner: root
      with_items:
        - ca.pem
        - "{{inventory_hostname}}-key.pem"
        - "{{inventory_hostname}}.pem"