- name: Proxmox VM Setup
  become: yes
  hosts: all

  tasks:
    - name: Handle dpkg locks and repair
      include_tasks: subtask_fix_dpkg_lock.yaml

    - name: Install QEMU Guest Agent
      apt:
        name: qemu-guest-agent
        state: latest
        force: yes
      register: apt_status
      until: apt_status is succeeded
      delay: 6
      retries: 30
      ignore_errors: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: full
        update_cache: yes
