- name: Download, install, and configure kubernetes Control plane
  hosts: k8s_controller
  become: yes
  vars:
    confpath: "/etc/kubernetes/config"
    instpath: "/usr/local/bin"
    datapath: "/var/lib/kubernetes"
    org: kubernetes
    repo: kubernetes
    filenames:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - kubectl
    version: v1.21.3
    project_url: "https://storage.googleapis.com/kubernetes-release/release/{{version}}/bin/linux/amd64"
    # Kube networking
    SERVICE_CLUSTER_CIDR: "172.20.0.0/24"
    CLUSTER_CIDR: "172.18.0.0/16"
    # config vars holders
    all_hosts_but_this: []
    HOST_IP: {}
    PEERS_MAP: ""

  tasks:
    - name: Nginx
      block:
        # Make variables for the Kubernetes configfile
        - name: "check if /etc/nginx/sites-available exists"
          file:
            path: "/etc/nginx/sites-available"
            state: directory
            mode: 0755

        - name: apt nginx install
          apt:
            name: nginx
            state: present
            update_cache: yes

        - name: nginx config
          copy:
            dest: "/etc/nginx/sites-available/kubernetes.default.svc.cluster.local"
            src: "files/nginx/kubernetes.default.svc.cluster.local"
            mode: 0644

        - name: enable and restart nginx
          systemd:
            name: "{{item}}"
            state: restarted
            enabled: true
            daemon_reload: true
          with_items:
            - nginx

    - name: Kubernetes
      block:
        - name: "check if {{ datapath }} exists"
          file:
            path: "{{ datapath }}"
            state: directory
            mode: 0700
            group: root
            owner: root

        - name: "check if {{ instpath }} exists"
          file:
            path: "{{ instpath }}"
            state: directory
            mode: 0755

        - name: "check if {{ confpath }} exists"
          file:
            path: "{{ confpath }}"
            state: directory
            mode: 0700
            group: root
            owner: root

        - name: "installing {{ repo }} {{ version }}"
          with_items: "{{filenames}}"
          get_url:
            url: "{{project_url}}/{{ item }}"
            dest: "{{ instpath }}/{{ item }}"
            mode: 0755

    - name: Kube SystemD templates
      block:
        # Make variables for the Kubernetes configfile
        - name: Get IP for all hosts, store in HOST_IP
          set_fact:
            HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
          loop: "{{ groups['etcd'] }}"

        - name: Flatten dict to formatted string, store ETCD_SERVER_URLS
          set_fact:
            ETCD_SERVER_URLS: "{{ PEERS_MAP }}{{ (index > 0)|ternary(',','') }}https://{{ item.value }}:2379"
          loop: "{{  HOST_IP | dict2items }}"
          loop_control:
            index_var: index

        # Create the config file from template
        - name: systemd service
          copy:
            dest: "/etc/systemd/system/{{item}}.service"
            content: '{{ lookup("template", "files/kubernetes/{{item}}.service.j2") }}'
            mode: 0644
            group: root
            owner: root
          with_items:
            - kube-apiserver
            - kube-scheduler
            - kube-controller-manager

        - name: kube-scheduler yaml
          copy:
            dest: "/etc/kubernetes/config/kube-scheduler.yaml"
            src: "files/kubernetes/kube-scheduler.yaml"
            mode: 0644
            group: root
            owner: root

        - name: enable and restart kubernetes
          systemd:
            name: "{{item}}"
            state: restarted
            enabled: true
            daemon_reload: true
          with_items:
            - kube-apiserver
            - kube-controller-manager
