- name: Kubernetes And all related tools
  become: yes
  hosts: all
  vars:
    containerd_install: '/usr/local/src/'
  tasks:

  - name: System
    block:

    - name: Seconds since last apt-get update
      shell: echo $(($(date +"%s") - $(stat -c %Y /var/cache/apt/)))
      register: apt_get_update_secs

    # host level switches and all that
    - name: swapp-off fstab
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: swapp-off command
      shell: swapoff -a

    - name: overlay br_netfilter
      shell: modprobe overlay br_netfilter


  - name: ContainerD
    block:

    - name: apt packages needed for containerd
      apt:
        pkg:
          [ golang, gcc, containerd ]

    - name: generate vanilla containerd config
      shell: containerd config default
      register: containerd_config

    - name: mkdir /etc/containerd
      file:
        path: /etc/containerd
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: generate vanilla containerd config
      when: containerd_config.stdout | length > 0
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: daemon-reload
      shell: systemctl daemon-reload

    - name: Enable and Start Containerd
      systemd:
        enabled: yes
        state: started
        name: containerd

  - name: Kubelet and Kubeadm
    block:

    - name: Kubernetes.io tooling
      apt:
        pkg:
          [ kubelet, kubeadm, kubectl ]

  - name: Kubernetes
    block:

    - name: kube-sysctls
      copy:
        src: sysctl.d_kubernetes.conf
        dest: /etc/sysctl.d/kubernetes.conf

    - name: daemon-reload
      shell: systemctl daemon-reload

    - name: sysctl reload
      shell: sysctl --system
