---
- name: Install Pi-hole on Debian 12
  hosts: pi-hole
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: true

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - procps
        - lsb-release

    - name: Add Pi-hole repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.pi-hole.net/debian {{ ansible_distribution_release }} main
        state: present
        filename: pihole

    - name: Install Pi-hole
      ansible.builtin.apt:
        name: pi-hole
        state: present

    - name: Configure Pi-hole
      ansible.builtin.command: pihole -r
      environment:
        AUTO_INSTALL: 1

    - name: Restart DNS and Web services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - pihole-FTL
        - lighttpd

    - name: Update Pi-Hole
      ansible.builtin.command: pihole -u

    - name: Enable Pi-hole at startup
      ansible.builtin.systemd:
        name: pihole-FTL
        enabled: true

    - name: Set Pi-hole admin password
      ansible.builtin.command: pihole -a -p "{{ your_admin_password }}"
      environment:
        PIHOLE_SKIP_OS_CHECK: 1
      no_log: true

