---
- name: Loop over all users and call user_template playbook
  hosts: all
  vars_files:
    - vars_users.yaml
  tasks:
    - name: Sudo group gets passwordless sudo access
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- name: Global oh-my-zsh shell, theme, and vimrc
  become: yes
  block:

  - name: check oh_my_zsh installed
    changed_when: false
    stat:
      path: /usr/share/oh-my-zsh
    register: oh_my_zsh_installed

  - name: install oh my zsh as root
    when: oh_my_zsh_installed.stat.isdir == 'false'
    command: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

  - name: move oh-my-zsh to /usr/share
    when: oh_my_zsh_installed.stat.isdir == 'false'
    command: mv /root/.oh-my-zsh /usr/share/oh-my-zsh

  - name: copy zshrc template
    when: oh_my_zsh_installed.stat.isdir == 'false'
    command: cp /usr/share/oh-my-zsh/templates/zshrc.zsh-template /usr/share/oh-my-zsh/zshrc

  - name: /etc/skel zshrc symlink
    when: oh_my_zsh_installed.stat.isdir == 'false'
    command: ln /usr/share/oh-my-zsh/zshrc /etc/skel/.zshrc

  - name: check p10k installed
    changed_when: false
    shell: grep powerlevel10k /usr/share/oh-my-zsh/custom/themes/powerlevel10k | echo
    register: p10k_installed

  - name: install powerlevel10k
    when: not p10k_installed.stdout
    git:  repo=https://gitee.com/romkatv/powerlevel10k.git
          dest=/usr/share/oh-my-zsh/custom/themes/powerlevel10k
          accept_hostkey=yes
          force=yes
          depth=1

  - name: Set p10k THEME in .zshrc
    when: not p10k_installed.stdout
    lineinfile:
      path: /etc/skel/.zshrc
      state: present
      backrefs: yes
      regexp: '^ZSH_THEME=.*$'
      line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
      line: \g<1>:{{ }}
      validate: source /etc/skel/.zshrc

  - name: p10k config and state
    when: not p10k_installed.stdout
    copy:
      src: files/p10k.zsh
      dest: /etc/skel/.p10k.zsh

  - name: check ultimate vim installed
    changed_when: false
    stat:
     path: /etc/skel/.vim_runtime
    register: ultimate_vim_installed

  - name: ultimate vim
    when: not ultimate_vim_installed.stat.isdir is defined
    command: "{{ local_item }}"
    with_items:
      - git clone --depth=1 https://github.com/amix/vimrc.git /etc/skel/.vim_runtime
      - mkdir -p /usr/share/vim_runtime
      - cmod -R 1755 /usr/share/vim_runtime
      - sh /tmp/.vim_runtime/install_awesome_vimrc.shsh /etc/skel/.vim_runtime/install_awesome_vimrc.sh
      - cp /root/.vimrc /etc/skel
    loop_control:
      loop_var: local_item

  - name: tmux conf
    copy:
      src: files/tmux.conf
      dest: ~{{ user.name }}/.tmux.conf

  - name: Ensures /etc/skel/.config/glances path exists
    file: path=/etc/skel/.config/glances state=directory

  - name: Glances conf
    copy:
      src: files/glances.conf
      dest: /etc/skel/.config/glances/glances.conf

  - name: add each user one at a time with some custom setup
    include_tasks: subtask_user.yaml
    loop: "{{ user }}"
