- name: Kubernetes And all related tools
  hosts: all
  tasks:
  - name: Seconds since last apt-get update
    shell: echo $(($(date +"%s") - $(stat -c %Y /var/cache/apt/)))
    register: apt_get_update_secs

  - name: Kubernetes.io
    become: yes
    block:
    - name: Download containerd
      get_url:
        url: https://github.com/containerd/containerd/archive/v1.4.3.zip
        dest: /tmp/containerd.zip

    - name: containerd unzip
      command:  unzip -o /tmp/containerd.zip -d /usr/local

    - name: copy systemd unit file to proper place
      shell: cp /usr/local/containerd*/containerd.service /etc/systemd/system

    - name: latest version of containerd path
      shell: find /usr/local/ -maxdepth 1 -type d -name "containerd*" | sort | tail -n1
      register: containerd_path

    - name: add containerd location to path
      lineinfile:
        path: /etc/environment
        state: present
        backrefs: yes
        regexp: ^(PATH=.*)
        line: \g<1>:{{ containerd_path }}
        validate: "source /etc/environment"

    - name: generate vanilla containerd config
      shell: containerd config default > /etc/containerd/config.toml

    - name: discover Containerd unit file
      shell: systemctl daemon-reload

    - name: Enable and Start Containerd
      systemd:
        enabled: yes
        state: started
        name: containerd