- name: Gleaming the Kube™
  hosts: local
  vars:
    cfssl: "files/cfssl"
    cluster_name: k8s
    kubernetes_public_address: 192.168.1.101

  tasks:
  - name: Every Kube Needs a Config
    block:

    - name: Worker Configs
      delegate_to: localhost
      include: "./subtask_kubeconfig_worker.yaml"
      with_inventory_hostnames:
        - k8s_worker

    - name: Kube-Proxy Config
      delegate_to: localhost
      include: "./subtask_kubeconfig_proxy.yaml"
      with_items:
        - "kube-proxy"

    - name: Kube-Controller-Manager Config
      delegate_to: localhost
      include: "./subtask_kubeconfig_controller_mgr.yaml"
      with_items:
        - "kube-controller-manager"

    - name: Kube-Scheduler Config
      delegate_to: localhost
      include: "./subtask_kubeconfig_kube_scheduler.yaml"
      with_items:
        - "kube-scheduler"

    - name: Kube-Admin User Config
      delegate_to: localhost
      include: "./subtask_kubeconfig_kube_scheduler.yaml"
      with_items:
        - "admin"