- name: Nvidia Driver, encoding patch, and Containerd config
  hosts: all
  vars:
    nvidia_version: "495.46"
    # nvidia_version: 510

  tasks:
  - name: Driver and Patch
    become: yes
    when: nvidia_gpu is defined

    block:
    - name: stop  services using driver
      ansible.builtin.systemd:
        state: stopped
        daemon_reload: true
        name: "{{item}}"
      ignore_errors: true
      with_items:
        - containerd
        - kubelet

    - name: print debug
      debug:
        msg: "Installing {{nvidia_version}} driver"

    - name: blacklist the nuevo driver
      copy:
        dest: /etc/modprobe.d/blacklist-nvidia-nouveau.conf
        content: |
          blacklist nouveau
          options nouveau modeset=0
        force: yes
        mode: 0644
        group: root
        owner: root

    - name: download nvidia binary installer
      get_url:
        url: "https://international.download.nvidia.com/XFree86/Linux-x86_64/{{nvidia_version}}/NVIDIA-Linux-x86_64-{{nvidia_version}}.run"
        dest: "/tmp/NVIDIA-Linux-x86_64-{{nvidia_version}}.run"
        mode: 0755
        owner: root
        group: root

    - name: unload kernel drivers
      ignore_errors: true
      command: rmmod "{{item}}"
      with_items:
      - nouveau

    - name: set kernel version
      register: kernel_version
      shell:
        cmd: uname -r

    - name: apt install kernel headers
      apt:
        update_cache: true
        pkg: "linux-headers-{{kernel_version.stdout}}"

    - name: install nvidia driver from binary
      ignore_errors: yes
      shell: /tmp/NVIDIA-Linux-x86_64-"{{nvidia_version}}".run -a -n -s --systemd -z --no-x-check -b -r

    - name: add nvidia apt gpg key
      apt_key:
        url: "{{item}}"
      with_items:
      - https://nvidia.github.io/nvidia-container-runtime/gpgkey
      - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub

    - name: nvidia-container-runtime apt repo
      register: nvidia_apt_repo
      get_url:
        url: https://nvidia.github.io/nvidia-container-runtime/ubuntu20.04/nvidia-container-runtime.list
        dest: /etc/apt/sources.list.d/nvidia-container-runtime.list

    - name: apt install nvidia packages
      apt:
        update_cache: true
        force_apt_get: true
        allow-unauthenticated: true
        pkg:
        - "nvidia-utils-{{nvidia_version.split('.')[0]}}"
        - nvidia-container-runtime

    - name: run nvidi-smi test
      shell:
        cmd: nvidia-smi

    - name: make sure nvidia kernel module is listed at boot
      copy:
        dest: /etc/modprobe.d/nvidia.conf
        content: |
          # install nvidia nvidia-modprobe -c 0 -c 1
        force: yes
        mode: 0644
        group: root
        owner: root

    - name: Write Containerd config
      copy:
        force: yes
        content: '{{ lookup("template", "files/containerd/default.toml.j2") }}'
        dest: /etc/containerd/config.toml

    - name: update init ramfs
      shell:
        cmd: update-initramfs -u

    - name: Re-start related services
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: "{{item}}"
      ignore_errors: true
      with_items:
        - containerd
        - kubelet
