- name: root and system level
  hosts: all
  vars:
    new_paths: '/usr/local/go/bin'

  tasks:
  - name: Seconds since last apt-get update
    shell: echo $(($(date +"%s") - $(stat -c %Y /var/cache/apt/)))
    register: apt_get_update_secs

  - name: Stop snapd
    systemd:
      state: "{{ item }}"
      name: snapd
    with_items:
      - stopped
      - disabled

  - name: base packages
    become: yes
    block:
    - name: apt-get update
      # when: apt_get_update_secs.stdout|int > 1800
      apt: update_cache=yes

    - name: Install a suite of common tools
      apt:
        pkg:
          [
            golang, gcc, zsh, wget, curl, htop, iostat, iotop
            nmap, make, netcat, strace, fping, bmon, jq, yq, ccat
            iptraf-ng, tmux, glances, unzip, ntpdate
          ]

    - name: old_paths
      shell: awk -F \= '{print $2}' /etc/environment | sed -e 's/\:/\n/g' | sort -u | sed -e 's/\"//g' | xargs | sed -e 's/\ /:/g'
      register: old_paths

    - name: add go to the environment PATH
      lineinfile:
        path: /etc/environment
        state: present
        backrefs: yes
        regexp: '^PATH=.*'
        line: 'PATH={{ old_paths.stdout }}:{{ new_paths }}'

  - name: Set the Host TZ and hwclock to UTC
    community.general.timezone:
      hwclock: UTC
      name: UTC

  - name: copy ntpdate cron
    copy:
      src: files/crons/ntpdate.cron
      dest: /etc/cron.d/cron.ntpdate
      owner: root
      group: root
      mode: 0644

  - name: set time and date from NTP upstream
    shell: /usr/sbin/ntpdate time.nist.gov 