- name: KIND clusters
  hosts: all
  vars:
    kind_clusters:
    - consul
    - istio
    - linkerd
  tasks:
    - name: Make KIND for each type of software
      include_tasks: subtask_kind.yaml
      loop: "{{ kind_clusters }}"