- name: Kube 07 etcd
  hosts: etcd
  become: yes
  vars_files:
    - vars_kube.yaml

  vars:

  tasks:
    - name: Directories
      block:

      - name: MKdir "{{etcd_confpath}}"
        file:
          path: "{{etcd_confpath}}"
          state: directory
          mode: 0755
        with_items: [ "{{etcd_confpath}}", "{{etcd_datapath}}" ]

      - name: create tempdir
        tempfile:
          state: directory
          suffix: _dwnld
        register: tempfolder_1

      - name: Copy certs for etcd
        copy:
          force: yes
          src: "files/cfssl/{{item}}"
          dest: "{{etcd_confpath}}/{{item}}"
          mode: 0755
        with_items:
          - ca.pem
          - kubernetes-key.pem
          - kubernetes.pem

    - name: Download {{etcd_repo}} {{etcd_version}}
      block:

        - name: "installing {{ etcd_repo }} {{etcd_version}}"
          unarchive:
            remote_src: yes
            src: "{{etcd_project_url}}"
            dest: "{{tempfolder_1.path}}"
            keep_newer: yes
            extra_opts:
            - --strip=1
            - --no-anchored

        - name: mv files to bindir
          find:
            paths: "{{tempfolder_1.path}}"
            patterns: "etcd*"
          register: etcd_files

        - name: mv files to bindir
          command: mv "{{item.path}}" "{{etcd_binpath}}/{{item.path|basename}}-{{etcd_version}}"
          with_items:  "{{etcd_files.files}}"

        - name: chown files
          command: chown root:root "{{etcd_binpath}}/{{item.path|basename}}-{{etcd_version}}"
          with_items:  "{{etcd_files.files}}"

        - name: ln files to bindir
          command: ln -sf "{{etcd_binpath}}/{{item.path|basename}}-{{etcd_version}}" "{{etcd_binpath}}/{{item.path|basename}}"
          with_items:  "{{etcd_files.files}}"

        - name: rm tempdir
          file:
            state: absent
            name: "{{tempfolder_1.path}}"

    - name: Make EtcD systemd service
      block:
        - name: Get IP for a subset of hosts, store in HOST_IP
          set_fact:
            HOST_IP: "{{ HOST_IP | combine({ item: lookup('community.general.dig', item) }) }}"
          loop: "{{ groups['etcd'] }}"

        - name: Flatten dict to formatted string, store PEERS_MAP
          set_fact:
            PEERS_MAP: "{{ PEERS_MAP }}{{ (index > 0) | ternary(',','') }}{{ item.key }}=https://{{ item.value }}:2380"
          loop: "{{  HOST_IP | dict2items }}"
          loop_control:
            index_var: index

        # Create the config file from template
        - name: systemd Unit file copy to target
          copy:
            force: yes
            dest: "/etc/systemd/system/etcd.service"
            content: '{{ lookup("template", "files/etcd/etcd.service.j2") }}'
            mode: 0644
            group: root
            owner: root

        - name: enable and restart etcd service
          systemd:
            name: etcd
            state: restarted
            enabled: true
            daemon_reload: true
