---
- name: Bind9
  hosts: dns

  tasks:
  - name: bind and other packages
    become: yes
    block:

    - name: apt-get update
      apt: update_cache=yes

    - name: bind and tools
      apt:
        pkg:
          [ bind9, bind9utils, dnsutils]

    - name: rndc-key-write
      shell:
        creates: /etc/bind/rndc.key
        cmd: rndc-confgen -a -b 512

    - name: configs
      copy:
        force: yes
        src: bind9/{{ item  }}
        dest: /etc/bind/{{ item  }}
        owner: bind
        group: bind
        mode: 0644
      with_items:
        - named.conf.local
        - named.conf.options

    - name: make conf dirs
      file:
        path: /var/lib/bind/
        state: directory
        owner: bind
        group: bind
        mode: 0755

    # - name: zones
    #   copy:
    #     force: yes
    #     src: bind9/{{ item  }}
    #     dest:  /var/lib/bind/{{ item  }}
    #     owner: bind
    #     group: bind
    #     mode: 0644
    #   with_items:
    #     - cluster.local.zone
    #     - home.zone
    #     - db.rev.1.168.192.in-addr.arpa

    - name: write zone templates
      copy:
        force: yes
        dest: "/var/lib/bind/{{item}}"
        content: '{{ lookup("template", "files/bind9/{{item}}.j2") }}'
        mode: 0644
        owner: bind
        group: bind
      with_items:
        - home.zone
        - cluster.local.zone
        - db.rev.1.168.192.in-addr.arpa

    - name: Config Check
      shell: named-checkconf

    - name: Check home zone
      shell: named-checkzone  home /var/lib/bind/home.zone

    - name: Check reverse mapping zone
      shell: named-checkzone 1.168.192.in-addr.arpa /var/lib/bind/db.rev.1.168.192.in-addr.arpa

    - name: remove the jnl files before restart
      shell: find /var/lib/bind -type f -name "*.jnl" -delete

    - name: Enable and Start service
      systemd:
        enabled: yes
        state: restarted
        name: named
        daemon_reload: true
