- name: Kube 05.2 Dist Kubeconfigs Workers
  hosts: k8s_worker
  vars:
    k8s_dir: /var/lib/kubernetes
  vars_files:
    - vars_kube.yaml
  tasks:
  - name: Distribute the files made in previous steps
    become: yes
    block:

    - name: Ensure we have a directory to place files
      file:
        path: "{{ k8s_dir }}"
        mode: 0755
        owner: root
        group: root
        state: directory

    - name: Copy proxy and instance kubeconfig
      copy:
        dest: "{{ k8s_dir }}/{{ item }}"
        src: "files/kubeconf/{{item}}"
        mode: 0644
        group: root
        owner: root
      with_items:
        - "kube-proxy.kubeconfig"
        - "{{inventory_hostname}}.kubeconfig"