---
- name: Press Play... (Moby)
  hosts: all
  vars:
    dummy: Null

  tasks:
  - name: packages and config
    become: yes
    block:

    - name: apt-get update
      apt: update_cache=yes

    - name: DHCP server
      apt:
        pkg:
          [ isc-dhcp-server ]

    - name: rndc-key-check
      shell: cat /etc/bind/rndc.key
      register: rndc_keyfile

    - name: Failed rndc check
      when: rndc_keyfile.stdout | length <= 0
      fail:
        msg: "Try running the DNS bind9 setup or checking the /etc/bind/rndc.key on remote"

    - name: make conf dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: bind
        group: bind
        mode: 0755
      with_items:
        - /etc/dhcp
        - /etc/dhcp/rndc-keys/

    - name: rndc-key-copy
      when: rndc_keyfile.stdout | length > 0
      shell: cp /etc/bind/rndc.key /etc/dhcp/rndc-keys/rndc.key

    - name: Config files
      copy:
        src: isc-dhcp-server/{{ item  }}
        dest: "{{ item  }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - /etc/dhcp/dhcpd.conf
        - /etc/dhcp/kube-nodes.conf
        - /etc/default/isc-dhcp-server

    - name: Enable and Start service
      become: yes
      become_user: root
      systemd:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items:
        - isc-dhcp-server

  # kick the service, maybe this is NOT the first run?
    - name: restart service
      shell: systemctl restart isc-dhcp-server