- name: nuke kubernetes, ceph, and containers.
  hosts: k8s
  become: yes
  tasks:

  - name: stop all services
    ignore_errors: yes
    systemd:
      name: "{{item}}"
      state: stopped
      enabled: false
    with_items:
    - etcd
    - containerd
    - haproxy
    - kube-scheduler
    - kube-apiserver
    - kube-controller-manager
    - kubelet
    - kube-proxy

  # - name: Get kube-pods services
  #   shell: "systemctl status *kube* 2>/dev/null | grep ● | awk '{print $2}'"
  #   register: running_kube_systemd

  # - name: stop kube-pods
  #   ignore_errors: yes
  #   systemd:
  #     name: "{{item}}"
  #     state: stopped
  #   loop: "{{ running_kube_systemd.stdout.split('\n') }}"

  - name: Get running processes
    shell: "ps -ef | grep -v grep | grep container | awk '{print $2}'"
    register: running_processes

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"

  # - name: Waiting until all running processes are killed
  #   wait_for:
  #     path: "/proc/{{ item }}/status"
  #     state: absent
  #   with_items: "{{ running_processes.stdout_lines }}"

  - name: remove dirs
    ignore_errors: yes
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/containerd
    - /etc/etcd
    - /etc/haproxy
    - /run/containerd
    - /run/systemd/transient
    - /usr/libexec/kubernetes
    - /var/lib/containerd
    - /var/lib/etcd
    - /var/lib/kubelet
    - /var/lib/kubernetes
    - /var/lib/rook

  - name: copy ceph osd disk reset script
    copy:
      src: ceph/teardown.sh
      dest: /tmp/teardown.sh
      owner: root
      group: root
      mode: 0755

  - name: run ceph osd disk reset script for each disk
    ignore_errors: yes
    shell:
      cmd: /tmp/teardown.sh {{item}}
    with_items:
    - sda
    - sdb
    - sdc
    - sdd
    - sde
    - sdf
    - sdg

  - name: delete flannel links
    ignore_errors: yes
    shell:
      cmd: ip link delete {}
    with_items:
    - cni0
    - flannel.0
    - flannel.1
    - kube-ipvs0
    - kube-ipvs1
