- name: Kubelet Client CSR
  delegate_to: localhost
  template:
    src: files/cfssl/_instance-template-csr.json
    dest: "files/cfssl/{{ item }}-csr.json"

- name: Kubelet Client Certs
  delegate_to: localhost
  shell:
    cmd: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname={{item}} -profile=kubernetes {{item}}-csr.json | cfssljson -bare {{item}}"
    chdir: files/cfssl/