# Generate a kubeconfig file for the Kube-proxy
- name: Worker Kube-Proxy Config - Set Cluster
  delegate_to: localhost
  shell:
    chdir: "{{ cfssl }}"
    cmd: >-
      "kubectl config set-cluster {{ cluster_name }}"
      "--certificate-authority=ca.pem"
      "--embed-certs=true"
      "--server=https://{{ kubernetes_public_address }}:6443"
      "--kubeconfig={{ item }}.kubeconfig"

- name: Worker Kube-Proxy Config - Set Credentials
  delegate_to: localhost
  shell:
    chdir: "{{ cfssl }}"
    cmd: >-
      "kubectl config set-cluster system:kube-proxy"
      "--client-certificate={{ item }}.pem"
      "--client-keys={{ item }}-key.pem"
      "--embed-certs=true"
      "--kubeconfig={{ item }}.kubeconfig"

- name: Worker Kube-Proxy Config - Set Context
  delegate_to: localhost
  shell:
    chdir: "{{ cfssl }}"
    cmd: >-
      "kubectl config set-cluster default"
      "--cluster={{ cluster_name }}"
      "--user=system:{{ item }}"
      "--kubeconfig={{ item }}.kubeconfig"

- name: Worker Kube-Proxy Config - Use-Context
  delegate_to: localhost
  shell:
    chdir: "{{ cfssl }}"
    cmd: kubectl config use-context default --kubeconfig={{ item }}.kubeconfig