# Generate a kubeconfig file for the Kube-proxy
- name: Worker Kube-Proxy Config - Set Cluster
  delegate_to: localhost
  shell:
    cmd: >-
      kubectl config set-cluster "{{ cluster_name }}"
      "--certificate-authority={{ cfssl }}/ca.pem"
      "--embed-certs=true"
      "--server=https://127.0.0.1:6443"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Worker Kube-controller-manager Config - Set Credentials
  delegate_to: localhost
  shell:
    cmd: >-
      kubectl config set-credentials "system:{{ item }}"
      "--client-certificate={{ cfssl }}/{{ item }}.pem"
      "--client-key={{ cfssl }}/{{ item }}-key.pem"
      "--embed-certs=true"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Worker Kube-Proxy Config - Set Context
  delegate_to: localhost
  shell:
    cmd: >-
      kubectl config set-context default
      "--cluster={{ cluster_name }}"
      "--user=system:node{{ item }}"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Worker Kube-Proxy Config - Use-Context
  delegate_to: localhost
  shell:
    cmd: >-
      kubectl config use-context default
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"