- name: Create the user and ensure grpups and sudo (done as root)
  become: yes
  become_user: root
  block:
  - name: change iterable item -> user so item can be used in this playbook
    set_fact:
      user: '{{ item }}'

  - name: check for user
    changed_when: false
    shell: id "{{ user.name }}"
    register: user_exists

  - name: Add required base users
    when: user_exists.rc != 0
    user:
      name: "{{ user.name }}"
      comment: "{{ user.First user.Last}}"
      shell: /bin/zsh
      group: "{{ user.name }}"
      groups: "{{ user.groups }}"
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Add github keys to "{{ user.name }}"
    authorized_key:
      user: "{{ user.name }}"
      state: present
      key: "https://github.com/{{ user.github }}.keys"

- name: Installed as the user
  become: yes
  become_user: "{{ user.name }}"
  ignore_errors: yes
  block:

  - name: check oh_my_zsh installed
    changed_when: false
    stat:
      path: ~{{ user.name }}/.oh-my-zsh
    register: oh_my_zsh_installed

  - name: print vars
    ansible.builtin.debug:
      msg: "{{ oh_my_zsh_installed }}"

  - name: install oh my zsh
    changed_when: false
    when: oh_my_zsh_installed.stat.isdir == 'false'
    command: "{{ local_item }}"
    with_items:
    - curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
    loop_control:
      loop_var: local_item

  - name: check p10k installed
    changed_when: false
    shell: grep powerlevel10k ~{{ user.name }}/.zshrc | echo
    register: p10k_installed

  - name: install powerlevel10k
    when: not p10k_installed.stdout
    git:  repo=https://gitee.com/romkatv/powerlevel10k.git
          dest=~{{ user.name }}/.oh-my-zsh/custom/themes/powerlevel10k
          accept_hostkey=yes
          force=yes
          depth=1

  - name: Set p10k THEME in .zshrc
    when: not p10k_installed.stdout
    lineinfile:
      path: ~{{ user.name }}/.zshrc
      state: present
      backrefs: yes
      regexp: '^ZSH_THEME=.*$'
      line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
      line: \g<1>:{{ }}
      validate: source ~{{ user.name }}/.zshrc

  - name: p10k config and state
    when: not p10k_installed.stdout
    copy:
      src: files/p10k.zsh
      dest: ~{{ user.name }}/.p10k.zsh

  - name: check ultimate vim installed
    changed_when: false
    stat:
     path: ~{{ user.name }}/.vim_runtime
    register: ultimate_vim_installed

  - name: ultimate vim
    when: not ultimate_vim_installed.stat.isdir is defined
    command: "{{ local_item }}"
    with_items:
      - git clone --depth=1 https://github.com/amix/vimrc.git ~{{ user.name }}/.vim_runtime
      - sh ~{{ user.name }}/.vim_runtime/install_awesome_vimrc.sh
    loop_control:
      loop_var: local_item

  - name: tmux conf
    copy:
      src: files/tmux.conf
      dest: ~{{ user.name }}/.tmux.conf

  - name: Ensures ~{{ user.name }}/.config/glances/ path exists
    file: path=~{{ user.name }}/.config/glances/ state=directory

  - name: Glances conf
    copy:
      src: files/glances.conf
      dest: ~{{ user.name }}/.config/glances/glances.conf
