# Generate a kubeconfig file for the Kube-admin
- name: Kube-admin Config - Set Cluster
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: >-
      kubectl config set-cluster "{{ cluster_name }}"
      "--certificate-authority={{ cfssl }}/ca.pem"
      "--embed-certs=true"
      "--server=https://127.0.0.1:6443"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Kube-controller-manager Config - Set Credentials
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: >-
      kubectl config set-credentials "{{ item }}"
      "--client-certificate={{ cfssl }}/{{ item }}.pem"
      "--client-key={{ cfssl }}/{{ item }}-key.pem"
      "--embed-certs=true"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Kube-admin Config - Set Context
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: >-
      kubectl config set-context default
      "--cluster={{ cluster_name }}"
      "--user={{ item }}"
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"

- name: Kube-admin Config - Use-Context
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: >-
      kubectl config use-context default
      "--kubeconfig={{ kubeconfig }}/{{ item }}.kubeconfig"