- name: Create the user and ensure groups and sudo (done as root)
  become: yes
  become_user: root

  block:
  - name: change iterable item -> user so item can be used in this playbook
    ansible.builtin.set_fact:
      user: '{{ item }}'

  - name: check for user
    ansible.builtin.command: id "{{ user.name }}"
    changed_when: false
    ignore_errors: true
    register: user_exists

  - name: Create group
    ansible.builtin.group:
      name: "{{ user.name }}"
      state: present

  - name: Add required base users
    when: user_exists.rc != 0
    ansible.builtin.user:
      name: "{{ user.name }}"
      comment: "{{ user.first }} {{ user.last}}"
      shell: /bin/zsh
      group: "{{ user.name }}"
      groups: "{{ user.groups }}"
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Add github keys to "{{ user.name }}"
    ansible.builtin.authorized_key:
      user: "{{ user.name }}"
      state: present
      key: "https://github.com/{{ user.github }}.keys"

