- name: Experimental x-12
  hosts: localhost
  # vars:
  #   dirs:
  #     cni:
  #       conf: /etc/cni/net.d
  #       bin: /opt/cni/bin
  #     kubernetes:
  #       conf: /etc/kubernetes/config
  #       static: /etc/kubernetes/manifests
  #       data: /var/lib/kubernetes
  #       lock: /var/run/kubernetes
  #     system:
  #       bin: /usr/local/bin
  #     kube-proxy:
  #       data: /var/lib/kube-proxy

  tasks:

    - name: print debug
      debug:
        msg: "{{ lookup('community.general.random', base64=true, length=32) }}"
