- name: test interfaces
  hosts: all
  tasks:

  - name: register interfaces carrier
    shell: |
      grep -l 1 /sys/class/net/e*/carrier | xargs -n1 dirname | xargs -n1 basename
    register: carrier_up

  - name: populate iface dict
    set_fact:
      interfaces: "{{ interfaces|default([]) + [ {item: {}} ]  }}"
    with_items: "{{carrier_up.stdout.split('\n')}}"

  - name: debug print
    debug:
      msg: "{{interfaces}}"

  - name: register interfaces speeds
    shell: |
      grep -v -- -1 /sys/class/net/e*/speed | sed -e 's/\// /g' | xargs -n1 | egrep '(eth|speed)' | sed -e 's/speed://g' | xargs -n2
    register: iface_speed

  - name: debug print
    debug:
      msg: "{{ iface_speed.stdout.split('\n') }}"