# SSL PKI
cfssl: "files/cfssl"
pki_dir: /var/lib/kubernetes

# config vars holders
all_hosts_but_this: []
HOST_IP: {}
PEERS_IP: {}
PEERS_MAP: ""
ETCD_SERVER_URLS: ""

# Kube Cluster Meta
KUBE_CLUSER_NAME: "k8s"
KUBECONFIG: "kubeconfig"

# Kube networking
KUBERNETES_HOSTNAMES: "kubernetes.internal,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
APISERVER: "apiserver"
APISERVER_IP: ""
SERVICE_CLUSTER_CIDR: "172.20.0.0/24"
CLUSTER_CIDR: "172.18.0.0/16"
POD_CIDR: "172.19.0.0/16"