user:
  - name: terrac
    First: Terrac
    Last: Skiens
    groups: [sudo, docker]
    github: bluefishforsale
  - name: carret
    First: Carret
    Last: Sneiks
    groups: [sudo, docker]
    github: bluefishforsale