# support verions
ETCD_VERSION: "3.5.9"
RUNC_VERSION: "1.1.8"
CRI_UTIL_VERSION: "1.27.1"
CNI_PLUGIN_VERSION: "1.3.0"
CONTAINERD_VERSION: "1.7.2"

# SSL PKI
cfssl: files/cfssl
pki_dir: /var/lib/kubernetes

# etd
etcd_confpath: "/etc/etcd"
etcd_binpath: "/usr/local/bin"
etcd_datapath: "/var/lib/etcd"
etcd_org: etcd-io
etcd_repo: etcd
etcd_version: "v{{ETCD_VERSION}}"
etcd_filename: "{{etcd_repo}}-{{etcd_version}}-linux-amd64.tar.gz"
etcd_project_url: https://github.com/{{etcd_org}}/{{etcd_repo}}/releases/download/{{etcd_version}}/{{etcd_filename}}


# k8s control plane
controller_confpath: "/etc/kubernetes/config"
controller_instpath: "/usr/local/bin"
controller_datapath: "/var/lib/kubernetes"
controller_filenames:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl

# k8s workers
worker_dirs:
  cni:
    conf: /etc/cni/net.d
    bin: /opt/cni/bin
  kubernetes:
    conf: /etc/kubernetes/config
    static: /etc/kubernetes/manifests
    data: /var/lib/kubernetes
    lock: /var/run/kubernetes
  system:
    bin: /usr/local/bin
  kube-proxy:
    data: /var/lib/kube-proxy
worker_binaries:
  - kube-proxy
  - kubelet
  - kubectl

# GCP
homelab_gcp_account: "terracnsoaur@gmail.com"
homelab_project_name: "homelab-390805"
homelab_credentials_file: "{{ ansible_env.HOME }}/.config/gcloud/application_default_credentials.json"
homelab_service_account_name: "sa-homelab-admin@{{ homelab_project_name }}.iam.gserviceaccount.com"
homelab_keylab_location: global
homelab_sa_admin_credentials_file: "{{ ansible_env.HOME }}/.config/gcloud/sa-homelab-admin_credentials.json"
homelab_keyring: "projects/{{ homelab_project_name }}/locations/{{ homelab_keylab_location }}/keyRings/{{ homelab_sops_key_name }}"
homelab_pki_kms_secret: ""
homelab_sops_key_name: "homelab-sops-key"
homelab_cryptokey_name: "homelab-cryptokey"

# config vars holders
all_hosts_but_this: []
HOST_IP: {}
PEERS_IP: {}
PEERS_MAP: ""
ETCD_SERVER_URLS: ""

# Kube Cluster Meta
KUBE_URL: "https://storage.googleapis.com/kubernetes-release/release/{{KUBE_VERSION}}/bin/linux/amd64"
KUBE_CLUSER_NAME: "k8s"
KUBECONFIG: "kubeconfig"
KUBE_VERSION: "v1.27.4"

# Kube networking
kubeconfig: "files/kubeconf"
k8s_dir: /var/lib/kubernetes
cluster_name: k8s
KUBERNETES_HOSTNAMES: "kubernetes.internal,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
APISERVER: "apiserver"
SYSLOG: "192.168.1.65"
APISERVER_IP: ""
CLUSTER_CIDR: "10.0.0.0/16"
# due to the way the PodCIDR for the kubelet is configured, this must not be larger than /24 right not
# the last octet of the IP address as the 3rd octet of the kubernetes pod cidr eg kube601 = 192.168.1.65 = podCIDR 10.0.65.0
# and since the DNS and IP mappings are for sequential IP addresses this limits us to /24 for each node podCIDR
# cilium companion to this :https://github.com/bluefishforsale/homelab-kube/blob/master/charts/cilium/values.yaml#L1688-L1689
# kubelet compantion to this : https://github.com/bluefishforsale/homelab/blob/master/ansible/files/kubelet/kubelet-config.yaml.j2#L18
POD_NETMASK: "24"
SERVICE_CLUSTER_IP_RANGE: "10.0.250.0/20"
# this maps to an IP address in the kubelet config and coreDNS pod
# https://github.com/bluefishforsale/homelab-argocd/blob/master/charts/coredns/values.yaml#L70
# https://github.com/bluefishforsale/homelab/blob/master/ansible/files/kubelet/kubelet-config.yaml.j2#L13-L14
CLUSTER_DNS:  "10.0.0.10"