# SSL PKI
cfssl: "files/cfssl"
pki_dir: /var/lib/kubernetes

# config vars holders
all_hosts_but_this: []
HOST_IP: {}
PEERS_IP: {}
PEERS_MAP: ""
ETCD_SERVER_URLS: ""

# Kube networking
KUBERNETES_HOSTNAMES: "kubernetes.internal,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
APISERVER: "apiserver.home"
APISERVER_IP: ""
SERVICE_CLUSTER_CIDR: "172.20.0.0/24"
CLUSTER_CIDR: "172.18.0.0/16"