# SSL PKI
cfssl: files/cfssl
pki_dir: /var/lib/kubernetes

#GCP
homelab_gcp_account: "terracnsoaur@gmail.com"
homelab_project_name: "homelab-390805"
homelab_credentials_file: "{{ ansible_env.HOME }}/.config/gcloud/application_default_credentials.json"
homelab_service_account_name: "sa-homelab-admin@{{ homelab_project_name }}.iam.gserviceaccount.com"
homelab_keylab_location: global
homelab_sa_admin_credentials_file: "{{ ansible_env.HOME }}/.config/gcloud/sa-homelab-admin_credentials.json"
homelab_keyring: "projects/{{ homelab_project_name }}/locations/{{ homelab_keylab_location }}/keyRings/{{ homelab_sops_key_name }}"
homelab_pki_kms_secret: ""
homelab_sops_key_name: "homelab-sops-key"
homelab_cryptokey_name: "homelab-cryptokey"

# config vars holders
all_hosts_but_this: []
HOST_IP: {}
PEERS_IP: {}
PEERS_MAP: ""
ETCD_SERVER_URLS: ""

# Kube Cluster Meta
KUBE_URL: "https://storage.googleapis.com/kubernetes-release/release/{{KUBE_VERSION}}/bin/linux/amd64"
KUBE_CLUSER_NAME: "k8s"
KUBECONFIG: "kubeconfig"
KUBE_VERSION: "v1.27.4"

# support verions
ETCD_VERSION: "3.5.9"
RUNC_VERSION: "1.1.8"
CRI_UTIL_VERSION: "1.27.1"
CNI_PLUGIN_VERSION: "1.3.0"
CONTAINERD_VERSION: "1.7.2"

# Kube networking
KUBERNETES_HOSTNAMES: "kubernetes.internal,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
APISERVER: "apiserver"
SYSLOG: "192.168.1.65"
APISERVER_IP: ""
CLUSTER_CIDR: "10.244.0.0/16"
POD_NETMASK: "24"
SERVICE_CLUSTER_IP_RANGE: "10.32.0.0/24"