# handlers file for common
---
- name: enable_and_restart
  become: true
  ansible.builtin.systemd:
    enabled: "{{ item.enabled | default('true') }}"
    daemon_reload: "{{ item.reload | default('true') }}"
    state: "{{ item.state | default('restarted') }}"
    name: "{{ item.name }}"
  with_items: "{{ services }}"